aws-rds-globalcluster/README.md, aws-rds-globalcluster/aws-rds-globalcluster.json, aws-rds-globalcluster/src/main/java/software/amazon/rds/globalcluster/BaseHandlerStd.java, aws-rds-globalcluster/src/main/java/software/amazon/rds/globalcluster/DeleteHandler.java, aws-rds-globalcluster/src/main/java/software/amazon/rds/globalcluster/Translator.java, aws-rds-globalcluster/src/test/java/software/amazon/rds/globalcluster/DeleteHandlerTest.java, aws-rds-globalcluster/src/test/java/software/amazon/rds/globalcluster/TranslatorTest.java, aws-rds-globalcluster/src/test/java/software/amazon/rds/globalcluster/UpdateHandlerTest.java
verify that handlers return NotFound error code
when global cluster does not exist
verify that translator copies all properties
from model into request
add StorageEncrypted to the list of create only properties
=> add tests for update and delete handlers and translator

aws-rds-globalcluster/src/main/java/software/amazon/rds/globalcluster/CallbackContext.java, aws-rds-globalcluster/src/main/java/software/amazon/rds/globalcluster/DeleteHandler.java, aws-rds-globalcluster/src/test/java/software/amazon/rds/globalcluster/DeleteHandlerWithProgressTest.java
*AURORA-5700*
*Adds handler for IN_PROGRESS Response*
When DescribeGlobalCluster after deletion returns IN_PROGRESS the delete handler should not attempt to delete the global cluster again. Instead it should check repeatedly into the progress and return SUCCESS when the cluster is no longer present.
=> fix duplicate delete call

buildspec.yml
This commit updates the build spec in order to provide an explicit
version range for `six` pip package to ~>1.15 (>=1.15.0, <1.16.0).
The current pipeline comes with pip version 1.14.0, which is incompatible
with the new cfn-cli tool and breaks the build pipeline.
An example of a failing pipeline:
```
ERROR: aws-sam-translator 1.34.0 has requirement six~=1.15, but you'll have six 1.14.0 which is incompatible.
```
Providing a patch-level version range allows the pipeline to receive
patch versions with no need to change the spec again.
The version range must be bumped again upon an incompatible update
landing on cfn-cli side.
Signed-off-by: Oleg …
=> Pin `six` python package version to ~>1.15

.github/workflows/maven-verify.yml, aws-rds-dbparametergroup/src/main/java/software/amazon/rds/dbparametergroup/Configuration.java, aws-rds-dbparametergroup/src/main/java/software/amazon/rds/dbparametergroup/Translator.java
Removing Translator unused method and adding resource to Maven verify pipeline
Signed-off-by: Moataz Mohamed <azmoataz@amazon.com>
=> Removing Translator unused method from AWS::RDS::DbParamterGroup

aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/Translator.java
Re-creating PR: #52 
Issue #, if available: #15 
Also see linked issue:
aws-cloudformation/aws-cloudformation-coverage-roadmap#336
Description of changes:
This occurs as the dbSubnetGroupName field isn't included in translator function: restoreDbClusterToPointInTimeRequest.
The appropriate course of action here is to simply add the missing field.
Thanks for your patience
=> Cannot RestoreToPointInTime into specified subnets

aws-rds-optiongroup/.rpdk-config, aws-rds-optiongroup/pom.xml, aws-rds-optiongroup/src/main/java/software/amazon/rds/optiongroup/BaseHandlerStd.java, aws-rds-optiongroup/src/main/java/software/amazon/rds/optiongroup/CreateHandler.java, aws-rds-optiongroup/src/main/java/software/amazon/rds/optiongroup/ReadHandler.java, aws-rds-optiongroup/src/main/java/software/amazon/rds/optiongroup/UpdateHandler.java, aws-rds-optiongroup/src/test/java/software/amazon/rds/optiongroup/UpdateHandlerTest.java
This commit adds a support for system tags. Prior to that, OptionGroup
was supporting resource-level tags only. RDS API makes no distinction
between system- and resource-level tags, so the tags are merged into a
single collection before invoking the corresponding RDS API call.
Apart from this change, OptionGroup drops a support for tagging
soft-failing. As it was concluded internally, soft failing on tagging is
considered to be a deprecated mode, therefore it is not making its way
to the new implementation.
AWS SDK version was bumped to 2.16.54.
=> AWS::RDS::OptionGroup supports system tags

aws-rds-dbinstance/aws-rds-dbinstance.json, aws-rds-dbinstance/resource-role.yaml
This commit fixes permissions for DBInstance schema:
Adds:
+ rds:CreateDbInstanceReadReplica
+ rds:RebootDBInstance
+ rds:RestoreDbInstanceFromDbSnapshot
+ rds:DescribeDbEngineVersions
+ rds:DescribeDbParameterGroups
Removes:
* rds:ListTagsForResource
The motivation for this change is to align it with the current method
set that is being used in the codebase.
=> Fix DBInstance permissions

aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/TranslatorTest.java
This commit drops junit.framework test dependency from DBInstance. The dependency was added mechanically with no reasons and we should have favoured an already existing dependency on org.assertj.
=> Drop junit.framework dependency from AWS::RDS::DBInstance

aws-rds-dbinstance/inputs/inputs_1_create.json, aws-rds-dbinstance/inputs/inputs_1_update.json
This commit removes specific AZ from DBInstance contract tests.
The motivation is to make the tests region-independent and let RDS choose the AZ automatically.
=> Drop AZ from DBInstance contract tests

aws-rds-dbinstance/pom.xml, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/BaseHandlerStd.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/CreateHandler.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/DeleteHandler.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/UpdateHandler.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/error/ErrorCode.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/error/ErrorRuleSet.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/error/ErrorStatus.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/error/HandlerErrorStatus.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/error/IgnoreErrorStatus.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/error/OrErrorRuleSet.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/error/PlainErrorRuleSet.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/error/UnexpectedErrorStatus.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/CreateHandlerTest.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/DeleteHandlerTest.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/UpdateHandlerTest.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/error/ErrorCodeTest.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/error/ErrorRuleSetTest.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/error/ErrorStatusTest.java
This commit introduces a new mechanism for RDS API response error handling in
AWS::RDS::DBInstance resource.
The motivation for this change is to provide a contextual error handling instead
of the existing static 1-size-fits-all approach. In other words, the existing
approach handles API error codes the same way for all resource handlers (create,
update, delete), which can cause an unwanted effect.
Another reason for this change is to handle generic AwsServiceException class of
errors. RDS SDK exposes a limited range of dedicated exception classes, the rest
is reported using a generic AwsServiceException error with AwsErrorDetails
container attribute including the error code.
The new approach introduces the concept of error rule sets. A rule set is
supposed to consume an exception …
=> Implement AWS::RDS::DBInstance error rulesets

aws-rds-optiongroup/src/main/java/software/amazon/rds/optiongroup/CreateHandler.java, aws-rds-optiongroup/src/main/java/software/amazon/rds/optiongroup/UpdateHandler.java, aws-rds-optiongroup/src/test/java/software/amazon/rds/optiongroup/AbstractTestBase.java, aws-rds-optiongroup/src/test/java/software/amazon/rds/optiongroup/CreateHandlerTest.java
This commit changes OptionGroup Create handler behavior on a case when the
option configurations collection is empty. The old behavior used to call
UpdateOptionGroup anyways, which resulted in a 400 response from the API
backend. This commits turns this update into a conditional operation by checking
if the underlying collection of option configurations is non-empty.
=> Fix AWS::RDS::OptionGroup on empty option configurations

aws-rds-dbinstance/aws-rds-dbinstance.json, aws-rds-dbinstance/resource-role.yaml, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/BaseHandlerStd.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/CreateHandler.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/Translator.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/CreateHandlerTest.java
This commit changes the default `MultiAZ` flag behavior on restoring a db
instance from a snapshot. The previous behavior was consuming the flag from the
request object with no change.
In fact, the default value for `MultiAZ` flag is engine-dependent. Whereas for the
majority of the engines the default value would be set to false, SQLServer
engines supporting mirroring expect this value set to null upon a restore.
A new IAM policy `rds:DescribeDBSnapshots` has been added to Create handler
permissions.
=> Set default MultiAZ flag upon an AWS::RDS::DBInstance restore from snapshot

aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/Translator.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/TranslatorTest.java
This commit changes the way modify-db-instance request is built. By
default, `UseDefaultProcessorFeatures` and `ProcessorFeatures` should be
unset. Once either of these 2 differs upon a stack modification, we set
it explicitly in the request.
=> Set processorFeatures on modify-db-instance conditionally

aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/Translator.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/UpdateHandler.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/util/ImmutabilityHelper.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/util/ImmutabilityHelperTest.java
This commit adds an explicit DBInstance resource immutability check upon an
update.
The motivation for this change is to ensure the update can be updated to the
desired state. Otherwise a complete replacement is required.
The check logic is consolidated in a new utility class called
`ImmutabilityHelper`. The check is performed on a set of attributes:
* Common attributes (db instance identifier, database name etc)
* Engine
* MultiAZ
* PerformanceInsights
=> Check resource immutability on AWS::RDS::DBInstance update

aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/Translator.java
This commit adds a missing attribute `copyTagsToSnapshot` to CreateDBInstance
request.
=> Fix missing copyTagsToSnapshot on DBInstance create

aws-rds-dbinstance/aws-rds-dbinstance.json, aws-rds-dbinstance/resource-role.yaml
This commit adds a missing IAM permission to AWS::RDS::DBInstance that
is required to add associated roles to the instances.
=> Add missing iam:PassRole to DBInstance create and update

aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/UpdateHandler.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/util/ImmutabilityHelper.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/util/ImmutabilityHelperTest.java
This commit addresses a regression introduced by
https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-rds/pull/83
The regression is impacting contract test suite, forcing an early
error-status exit on some test cases.
RDS API handles AZ modifications fine, given AvailabilityZone is a
create-only parameter and MultiAZ is defined as conditionally immutable.
From this perspective there is no need to handle it here.
=> Fix regression in DBInstance introduced by immutability checks

aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/UpdateHandler.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/AbstractHandlerTest.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/UpdateHandlerTest.java
This commit addresses unsetting `MaxAllocatedStorage` property upon a DBInstance update.
Given a CFN template (state A):
```yaml
Resources:
DBInstance:
Type: AWS::RDS::DBInstance
Properties:
AllocatedStorage: 100
...
```
Provided an update (state B):
```yaml
Resources:
DBInstance:
Type: AWS::RDS::DBInstance
Properties:
AllocatedStorage: 100
MaxAllocatedStorage: 1000
...
```
Transition to state B will set `MaxAllocatedStorage` to 1000 and enable the autoscaling.
If `MaxAllowedStorage` is unset later in the template (transition back to state A or its equivalent), the current implementation will keep the property in place rather than unsetting it.
RDS API does not have an explicit request parameter to unset this property. The way to get around it is to set `MaxAllocatedStorage` to the …
=> Unset DBInstance MaxAllocatedStorage

aws-rds-cfn-common/src/main/java/software/amazon/rds/common/error/ErrorCode.java, aws-rds-cfn-common/src/main/java/software/amazon/rds/common/handler/Commons.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/BaseHandlerStd.java
This commit adds a new ErrorCode called `InternalFailure`. It is returned by RDS API in a case of a service event.
An additional change to DBInstance and DBInstance role stabilization logic: errors are handled by `Commons.handleException/3` instead of the custom local try-catch block because it fails with a stack trace and an internal error status if RDS API returns a 5xx response code.
=> Handle RDS InternalFailure

aws-rds-dbinstance/aws-rds-dbinstance.json, aws-rds-dbinstance/resource-role.yaml
This commit adds an additional set of FAS policies to DBInstance
requested permissions. In particular, the following policies are being
additionally requested:
* ec2:DescribeVpcAttribute
* ec2:DescribeSecurityGroups
* ec2:DescribeInternetGateways
* ec2:DescribeAvailabilityZones
* ec2:DescribeVpcs
* ec2:DescribeAccountAttributes
* ec2:DescribeSubnets
* iam:GetRole
* iam:ListRoles
The motivation for this change is to align the minimal requested FAS
policy set to the one elaborated in AWS documentation:
* https://aws.amazon.com/premiumsupport/knowledge-center/rds-iam-least-privileges/
* https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazonrds.html#amazonrds-actions-as-permissions
By submitting this pull request, I confirm that you can use, modify, copy, and …
=> Extend AWS::RDS::DBInstance FAS policies with EC2:Describe*

aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/BaseHandlerStd.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/DeleteHandler.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/DeleteHandlerTest.java
This PR addresses an issue with `DeleteHandler` where `DBSnapshotIdentifier` resource attribute is being copied to `FinalDBSnapshotIdentifier` `delete-db-instance` request attribute. The validation logic for these 2 attributes on RDS API side differs: whereas the former can be a fully-qualified ARN, the latter must be a plain identifier. The identifier copy part turned out to be inconsistent with the legacy implementation, hence this PR enforces a snapshot id re-generation upon a delete call.
This PR also changes the original behavior of `DeleteHandler` which used to ignore `InvalidParameterValue` error code. The fix changes this to throwing a terminal error so the customer can address the validation issue.
By submitting this pull request, I confirm that you can use, modify, copy, and …
=> [DBInstance] Fix never-stabilizing delete requests

aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/DeleteHandler.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/DeleteHandlerTest.java
This PR provides an alternative implementation for DBInstance
DeleteHandler. In particular, it removes a manual DeleteDBInstance
invocation, delegating it to a proxyInvocation.
We are removing an explicit handling of `DbInstanceDeletingException` as
it is being handled by `DELETE_DB_INSTANCE_ERROR_RULE_SET` already.
=> [DBInstance] Rework DeleteHandler to use EventChain

aws-rds-dbinstance/aws-rds-dbinstance.json, aws-rds-dbinstance/docs/README.md
This PR is addressing 3 major regressions introduced by the current implementation:
* DBName validation fails if the attribute contains an underscore
* DBSnapshotIdentifier validation fails if an ARN value is provided
* MasterUsername validation fails if the attribute contains an
undescore
The PR intoduces the corresponding changes to the schema.
=> [DBInstance] Fix errors in schema regex validators

aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/DeleteHandler.java, aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/Translator.java, aws-rds-dbcluster/src/test/java/software/amazon/rds/dbcluster/DeleteHandlerTest.java
RemoveFromGlobalGlobal cluster API only accept ClusterArn as DBClusterIdentifier. Otherwise it will throw malformed DBClusterIdentifier exception.
Ref: https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_RemoveFromGlobalCluster.html
Input Test stack:
```
{
"Description": "Basic DBCluster Template",
"Parameters": {
"DBClusterId": {
"Type": "String"
},
"GlobalClusterId": {
"Type": "String"
}
},
"Resources": {
"BasicDBCluster": {
"Type": "AWS::RDS::DBCluster",
"DeletionPolicy" : "Delete",
"Properties": {
"Engine": "aurora",
"MasterUsername": "guest",
"MasterUserPassword": "******",
"EngineVersion" : "5.6.mysql_aurora.1.22.2",
"DBClusterIdentifier": { "Ref": "DBClusterId" },
"GlobalClusterIdentifier": { "Ref": "GlobalClusterId" }
}
}
}
}
```
=> Use cluster arn in removing cluster from global cluster

aws-rds-cfn-common/src/main/java/software/amazon/rds/common/error/ErrorStatus.java, aws-rds-cfn-common/src/main/java/software/amazon/rds/common/error/IgnoreErrorStatus.java, aws-rds-cfn-common/src/main/java/software/amazon/rds/common/handler/Commons.java, aws-rds-cfn-common/src/test/java/software/amazon/rds/common/handler/CommonsTest.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/UpdateHandlerTest.java, aws-rds-optiongroup/src/main/java/software/amazon/rds/optiongroup/BaseHandlerStd.java
This PR changes the way `Commons` handler interprets `IgnoreErrorStatus` upon an exception handling. The current implementation always handles this code as an `in-progress` event. This cr makes it configurable and returns a success event by default instead.
The reason for this change is the fact that an in-progress event chain won't execute the upcoming `then` stage right away, but will spin up another event processing cycle. This creates an unwanted processing cycle in cases like DBInstance when associated roles are being added.
On the opposite side, a success-event could be a subject for an early return from the chain, even if the chain is intentionally terminated with `progress()` invoker. For this purpose `IgnoreErrorStatus` is made configurable so the end invoker can declare the …
=> [Common] Commons handler treats IgnoreErrorStatus as success

aws-rds-cfn-common/src/main/java/software/amazon/rds/common/handler/Commons.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/BaseHandlerStd.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/Translator.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/UpdateHandler.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/UpdateHandlerTest.java
This code change adds an alternative Update handler branch to facilitate a DBInstance resource drift resolution.
The change checks the request `Driftable` flag and performs a scatter-status check for the supporting objects. The check validates `in-sync` status for the following objects:
- DBParameterGroup
- OptionGroup
- DBClusterParameterGroup (if applicable)
Upon a complete sync, the handler would check if the instance requires a restart and performs a `reboot-await`.
=> [DBInstance] Handle drifting update requests

aws-rds-cfn-common/src/main/java/software/amazon/rds/common/error/ErrorCode.java, aws-rds-cfn-common/src/main/java/software/amazon/rds/common/handler/Tagging.java, aws-rds-cfn-common/src/test/java/software/amazon/rds/common/handler/TaggingTest.java, aws-rds-dbinstance/aws-rds-dbinstance.json, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/BaseHandlerStd.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/Configuration.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/CreateHandler.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/Translator.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/UpdateHandler.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/CreateHandlerTest.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/UpdateHandlerTest.java
This code change introduces a soft failing mechanism for stack-level tags upon a `DBInstance` update/create handler invocation.
The motivation for this change is to keep a complete backwards compatibility with the existing implementation. The point of interest is whether a customer has the corresponding IAM permissions:
- `rds:AddTagsToResource`
- `rds:RemoveTagsFromResource`
The current logic is:
- System tags are created and managed by CloudFormation. RDS API recognizes these tags and requires no extra IAM permissions to create these tags.
- Resource-level tags can only be provided by the customer, hence require both permissions mentioned above.
- Stack-level tags are declared by the customer but replicated to the resources by CloudFormation. In the light of the fact that distinct …
=> [DBInstance] Soft fail stack-level tag updates

aws-rds-dbcluster/inputs/inputs_1_create.json, aws-rds-dbcluster/inputs/inputs_1_invalid.json, aws-rds-dbcluster/inputs/inputs_1_update.json, aws-rds-dbclusterparametergroup/inputs/inputs_1_create.json, aws-rds-dbclusterparametergroup/inputs/inputs_1_invalid.json, aws-rds-dbclusterparametergroup/inputs/inputs_1_update.json, aws-rds-dbinstance/inputs/inputs_1_create.json, aws-rds-dbinstance/inputs/inputs_1_update.json, aws-rds-dbparametergroup/inputs/inputs_1_create.json, aws-rds-dbparametergroup/inputs/inputs_1_update.json, aws-rds-dbsubnetgroup/inputs/inputs_1_create.json, aws-rds-dbsubnetgroup/inputs/inputs_1_invalid.json, aws-rds-dbsubnetgroup/inputs/inputs_1_update.json, aws-rds-optiongroup/inputs/inputs_1_create.json, aws-rds-optiongroup/inputs/inputs_1_invalid.json, aws-rds-optiongroup/inputs/inputs_1_update.json
Renaming contract test identifiers input to include word `contract` so operator can relate created resource to contract test runs
=> [All]Rename Contract Tests Input Identifiers to Include `contract`

.gitignore, aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/BaseHandlerStd.java, aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/DeleteHandler.java, aws-rds-dbcluster/src/test/java/software/amazon/rds/dbcluster/DeleteHandlerTest.java
This code change enforces a final snapshot ID generate if a snapshot is requested. In contrast with the current implementation, where the ID generation was conditional (`DBSnapshotIdentifier` was reused), the new behavior generates a unique ID when a resource is being deleted.
The motivation for this change is to eliminate a customer snapshot override. This strategy was added by default and is seen wrong now.
=> [DBCluster] Force final snapshot ID generation upon a deletion

aws-rds-cfn-common/src/main/java/software/amazon/rds/common/test/AbstractTestBase.java, aws-rds-cfn-common/src/test/java/software/amazon/rds/common/test/AbstractTestBaseTest.java, aws-rds-dbcluster/aws-rds-dbcluster.json, aws-rds-dbcluster/docs/README.md, aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/Translator.java, aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/UpdateHandler.java, aws-rds-dbcluster/src/test/java/software/amazon/rds/dbcluster/UpdateHandlerTest.java
This PR changes the way `ModifyDBCluster` request attributes are being set. In particular, `Engine` and `MasterUserPassword` are being set conditionally.
`Engine` should only be set if the previous and the desired values differ and the stack is not undergoing a rollback. Otherwise RDS API will return an error "Cannot modify engine version without a healthy primary instance in DB cluster".
`MasterUserPassword` should only be set if the values differ.
=> [DBCluster] Set Engine and MasterUserPassword conditionally

aws-rds-cfn-common/src/main/java/software/amazon/rds/common/printer/FilteredJsonPrinter.java
This PR changes introduces an explicit import of Jackson JavaTimeModule library and registers it in the FilteredJsonPrinter ObjectMapper.
The reason for having this import and registration is because the module autoscan does not work under some build systems, e.g. Groovy. Maven picks this up just fine, but it is a non-generic approach. This code change ensures the import is enforced.
=> [Common] Register Jackson JavaTimeModule explicitly

aws-rds-dbinstance/aws-rds-dbinstance.json, aws-rds-dbinstance/docs/README.md, aws-rds-dbinstance/docs/tag.md, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/Translator.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/AbstractHandlerTest.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/CreateHandlerTest.java
This PR changes `port` attribute data type from integer to string. It seems the old implementation was using a string attribute, and the new implementation translated it into an integer. The fix is required as customers who were using string functions (e.g. `Fn::Join`) experienced a regression due to an argument of an invalid data type provided.
=> [DBInstance] Fix Port data type from integer to string

aws-rds-dbcluster/docs/tag.md, aws-rds-dbclusterparametergroup/docs/tag.md, aws-rds-dbclusterparametergroup/src/main/java/software/amazon/rds/dbclusterparametergroup/BaseHandlerStd.java, aws-rds-dbclusterparametergroup/src/main/java/software/amazon/rds/dbclusterparametergroup/Translator.java, aws-rds-dbclusterparametergroup/src/main/java/software/amazon/rds/dbclusterparametergroup/UpdateHandler.java, aws-rds-dbclusterparametergroup/src/test/java/software/amazon/rds/dbclusterparametergroup/CreateHandlerTest.java, aws-rds-dbclusterparametergroup/src/test/java/software/amazon/rds/dbclusterparametergroup/UpdateHandlerTest.java, aws-rds-dbparametergroup/docs/tag.md, aws-rds-dbsubnetgroup/docs/tag.md, aws-rds-eventsubscription/docs/tag.md, aws-rds-optiongroup/docs/tag.md
**Description of Change**
Current behavior in CloudFormation is to reset all parameters before doing modify because there is no efficient way to get DefaultDBClusterEngineParameters to compare with current parameters.
This PR puts resource handlers with sync with this behavior. 
Update handler now do this steps:
- Reset All parameters
- Modify target parameters
- Update tags
- Invoke read handler  
=> [DBClusterParameterGroup]Reset all parameters Before Modify

aws-rds-dbinstance/aws-rds-dbinstance.json, aws-rds-dbinstance/resource-role.yaml
Fix `RestoreDBInstanceFromDBSnapshot` permission in DBInstance
=> Fix `RestoreDBInstanceFromDBSnapshot` permission in DBInstance

aws-rds-dbinstance/aws-rds-dbinstance.json, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/Translator.java
This commit changes the data type definition for `Endpoint.Port`. The new implementation happened to copy the type definition from AWS RDS SDK, which declares this attribute as an Integer.
Having this fix in place will unblock customers using `Endpoint.Port` attribute in string functions.
=> [DBInstance] Fix Endpoint.Port datatype from Integer to String

aws-rds-cfn-common/src/main/java/software/amazon/rds/common/handler/Tagging.java, aws-rds-cfn-common/src/test/java/software/amazon/rds/common/handler/TaggingTest.java
Current behavior in cloudformation is resolving duplicate tag keys between stack level tags and resource tags by giving priority to resource tags.
This code change is to match this behavior for backward compatibility  
=> [Common] Handle Duplicate Tags Between StackLevelTags and ResourceTags.

aws-rds-dbparametergroup/src/main/java/software/amazon/rds/dbparametergroup/BaseHandlerStd.java, aws-rds-dbparametergroup/src/test/java/software/amazon/rds/dbparametergroup/CreateHandlerTest.java
We noticed there are extra parameters appeared in DBParameterGroup and not in DefaultEngineParameters. Current behavior in CloudFormation is ignoring these parameters.
=> [DBParameterGroup]  Matching Current CloudFormation Behaviour in Calculating Parameters to Reset

aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/UpdateHandler.java
This commit removes an engine set enforcement from the UpdateHandler. The reason be: `ModifyDBInstance` never updates the engine name itself: it only checks if there is an engine name change and triggers a replacement cycle if this is the case.
Setting an engine in this part of the code caused a regression under which the handler invoked `ModifyDBInstance` request once and failed upon a stabilization right away as `ensureEngineSet` invocation updated the desired resource model by reference. A close review of this code indicates that setting the engine name here is a no-op, hence it is removed.
=> [DBInstance] Disable engine setting upon an update

aws-rds-dbparametergroup/src/main/java/software/amazon/rds/dbparametergroup/BaseHandlerStd.java, aws-rds-dbparametergroup/src/test/java/software/amazon/rds/dbparametergroup/CreateHandlerTest.java
Some engines like `MariaDB` have 
- Extra current parameters that not found in default engine parameters.
- Extra default parameters that not found in current parameters.
Current cloudformation behavior is to ignore both of them. This change will meet this behavior by calculating parameters to reset from intersection between current and default only. That's mean any extra parameters in two of them will be ignored in resetting  
=> [DBParameterGroup] Calculating Parameters to Reset on Intersection Between Current Parameters and Default Parameters

aws-rds-dbcluster/aws-rds-dbcluster.json, aws-rds-dbcluster/docs/README.md, aws-rds-dbinstance/docs/README.md, aws-rds-dbsubnetgroup/aws-rds-dbsubnetgroup.json, aws-rds-dbsubnetgroup/docs/README.md
This commit incorporates 3 changes:
- Adds mysql and postgres to DBCluster schema: the current implementation only declares aurora engine types
- Changes DBSubnetGroup name length constraint from 256 to 255
- Regenerated README files for all resources to reflect the most recent changes to the resource definition schemas
=> [DBCluster] Add mysql and postgres to DBCluster schema engines +2

aws-rds-dbcluster/aws-rds-dbcluster.json
This commit alters the validator for conditionally required `MasterUsername` and `MasterUserPassword`: providing `GlobalClusterIdentifier` lets keeping these attributes empty.
=> [DBCluster] Change schema validation

aws-rds-eventsubscription/src/main/java/software/amazon/rds/eventsubscription/BaseHandlerStd.java, aws-rds-eventsubscription/src/main/java/software/amazon/rds/eventsubscription/CallbackContext.java, aws-rds-eventsubscription/src/main/java/software/amazon/rds/eventsubscription/CreateHandler.java, aws-rds-eventsubscription/src/main/java/software/amazon/rds/eventsubscription/ReadHandler.java, aws-rds-eventsubscription/src/main/java/software/amazon/rds/eventsubscription/Translator.java, aws-rds-eventsubscription/src/main/java/software/amazon/rds/eventsubscription/UpdateHandler.java, aws-rds-eventsubscription/src/test/java/software/amazon/rds/eventsubscription/CreateHandlerTest.java, aws-rds-eventsubscription/src/test/java/software/amazon/rds/eventsubscription/UpdateHandlerTest.java
Soft fails means ignoring permission denied exception and proceed with resource logic.This PR implements soft fail in EventSubscription:
- Hard fail on add/remove resource tags
- Soft fail on add/remove system tags
- Soft fail on add/remove stack level tags
- Soft fail on read tags
=> [EventSubscription] Implement soft fail in create, update, and read

aws-rds-cfn-common/src/main/java/software/amazon/rds/common/handler/HandlerConfig.java
This commit updates the default request chain timeout from `60` to `90` minutes. It seems some db instances time out to stabilize within 1hr if it observes a stabilization interruption. The stabilization for DBInstance is n-probed: the handler expects to observe 3 `available` statuses before it declares a stable state. If the counter is reset due to an interrupting instance reboot or upgrade, the handler will reset the probe counter and start it over. We are extending this default timeout in order to cover slow-provisioning cases.
=> [DBInstance] Increase default handler request chain timeout

aws-rds-dbparametergroup/src/main/java/software/amazon/rds/dbparametergroup/BaseHandlerStd.java, aws-rds-dbparametergroup/src/main/java/software/amazon/rds/dbparametergroup/ReadHandler.java, aws-rds-dbparametergroup/src/main/java/software/amazon/rds/dbparametergroup/Translator.java, aws-rds-dbparametergroup/src/main/java/software/amazon/rds/dbparametergroup/UpdateHandler.java, aws-rds-dbparametergroup/src/test/java/software/amazon/rds/dbparametergroup/UpdateHandlerTest.java
Implementing soft failing while doing `DescribeDBPrameterGroups` call to be backward compatible with current CloudFormation customer to prevent `AccessDenied` exception for existing stacks.
Changes:
- Compose `DBParameterGroupArn` from `Request` and `ResourceModel` instead of retrieving it from `DescribeDBPrameterGroups` call.
- Remove `fetchDBParameterGroupArn` as it triggers `DescribeDBPrameterGroups` call.
- Apply `setDBParameterGroupArn` in all handlers.
- Use in progress soft fail error rule set while executing `DescribeDBPrameterGroups` call in read handler.
- Update relative unit tests.
=> [DBParameterGroup]Soft fail for `DescribeDBParameterGroups` call

aws-rds-dbinstance/aws-rds-dbinstance.json, aws-rds-dbinstance/docs/README.md
This commit removes the enum-based validator that was defined on `StorageType` attribute previously. The reason for the removal is because CFN performs a case-sensitive enum lookup, so the values in different case spelling would be rejected.
A case-insensitive enum would rather be an option on CFN side, hence this commit could be rejected once ignore-case check is supported by CFN.
=> [DBInstance] Remove `StorageType` enum-based validator

aws-rds-dbinstance/aws-rds-dbinstance.json, aws-rds-dbinstance/docs/README.md
This commit alters the maxlen constraint for `MasterUsername` from 16 characters to 128 max. The reason for change is that initially DBInstance schema was aiming for the minimum length across all engines, but it causes validation failures on engines where longer usernames are allowed.
According to https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-database-instance.html#cfn-rds-dbinstance-masterusername, the maxlen across all engines is 128 characters. If a csutomer provides
a username that is longer than the engine maxlen but below 128 characters, the value would be sent to RDS API and rejected by the backend on contrast to rejecting by the the CFN validator. We believe this is a reasonable tradeoff that would allow us to include all engine constraints.
By …
=> [DBInstance] Increase MasterUsername maxlen constraint

aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/CreateHandler.java
This commit increases the execution chain timeout for `CreateHandler`. The reason for this change is to smooth out eventual RDS workflow slowness and eliminate stack creation timeouts.
The value is being bumped to 3hrs. Previously it was using the default timeout of 90 minutes.
=> [DBInstance] Increase CreateHandler timeout to 3hrs

aws-rds-dbsubnetgroup/src/main/java/software/amazon/rds/dbsubnetgroup/BaseHandlerStd.java, aws-rds-dbsubnetgroup/src/main/java/software/amazon/rds/dbsubnetgroup/CallbackContext.java, aws-rds-dbsubnetgroup/src/main/java/software/amazon/rds/dbsubnetgroup/CreateHandler.java, aws-rds-dbsubnetgroup/src/main/java/software/amazon/rds/dbsubnetgroup/DeleteHandler.java, aws-rds-dbsubnetgroup/src/main/java/software/amazon/rds/dbsubnetgroup/ListHandler.java, aws-rds-dbsubnetgroup/src/main/java/software/amazon/rds/dbsubnetgroup/ReadHandler.java, aws-rds-dbsubnetgroup/src/main/java/software/amazon/rds/dbsubnetgroup/Translator.java, aws-rds-dbsubnetgroup/src/main/java/software/amazon/rds/dbsubnetgroup/UpdateHandler.java, aws-rds-dbsubnetgroup/src/test/java/software/amazon/rds/dbsubnetgroup/CreateHandlerTest.java, aws-rds-dbsubnetgroup/src/test/java/software/amazon/rds/dbsubnetgroup/ReadHandlerTest.java, aws-rds-dbsubnetgroup/src/test/java/software/amazon/rds/dbsubnetgroup/UpdateHandlerTest.java
Soft fails means ignoring permission denied exception and proceed with resource logic. This PR implements soft fail in `DbSubnetGroup` resource:
- Hard fail on add/remove resource tags
- Soft fail on add/remove system tags
- Soft fail on add/remove stack level tags
- Soft fail on read tags
=> [DBSubnetGroup] Implement Soft Failing While Tagging Resource

aws-rds-dbcluster/docs/README.md, aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/ModelAdapter.java
This commit removes the code that sets the default DBCluster parameter group name upon creation. The reason for change is that RDS API picks up the default parameter group name automatically depending on the engine version. The previous implementation hardcoded the group name to `default.aurora5.6`, which caused troubles on other engine versions.
=> [DBCluster] Remove default parameter group name set on cluster create

aws-rds-dbparametergroup/aws-rds-dbparametergroup.json, aws-rds-dbparametergroup/src/main/java/software/amazon/rds/dbparametergroup/BaseHandlerStd.java, aws-rds-dbparametergroup/src/main/java/software/amazon/rds/dbparametergroup/Translator.java, aws-rds-dbparametergroup/src/main/java/software/amazon/rds/dbparametergroup/UpdateHandler.java, aws-rds-dbparametergroup/src/test/java/software/amazon/rds/dbparametergroup/AbstractTestBase.java, aws-rds-dbparametergroup/src/test/java/software/amazon/rds/dbparametergroup/CreateHandlerTest.java, aws-rds-dbparametergroup/src/test/java/software/amazon/rds/dbparametergroup/UpdateHandlerTest.java
In create only scenario, We do not need to calculate parameters to reset or describe current DB parameters as `DBParameterGroup` is recently created and all parameter will have same default values.
In this change:
- Rename old `applyParmeters` to more specific name `applyParameterWithReset`.
- Add new simple `applyParameter` method that
- Describe `DefaultDBParameters`.
- Validate input parameters against `DefaultDBParameters`.
- Modify input parameters in stack.
- Update create handler permission in resource schema
- Add/Update related unit tests.   
=> [DBParameterGroup] Fix DescribeDBParameters PermissionDenied Issue in Create Only Scenario

aws-rds-dbclusterparametergroup/src/main/java/software/amazon/rds/dbclusterparametergroup/BaseHandlerStd.java, aws-rds-dbclusterparametergroup/src/main/java/software/amazon/rds/dbclusterparametergroup/CreateHandler.java, aws-rds-dbclusterparametergroup/src/test/java/software/amazon/rds/dbclusterparametergroup/AbstractTestBase.java, aws-rds-dbclusterparametergroup/src/test/java/software/amazon/rds/dbclusterparametergroup/CreateHandlerTest.java
In this PR:
- Setting Arn at done in CreateHandler.
- Sending already created context in BaseHandler handle request method.  
- Update related unit test.
=> [DBClusterParameterGroup] Fix Missing Arn In Update Scenario

aws-rds-dbcluster/aws-rds-dbcluster.json, aws-rds-dbcluster/docs/README.md
This commit relaxes the validation constraint for `MasterUsername` attribute for the sake of simplifying engine-specific attribute checks.
=> [DBCluster] Remove upper length constraint for `MasterUsername`

aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/Translator.java, aws-rds-dbcluster/src/test/java/software/amazon/rds/dbcluster/CreateHandlerTest.java
This commit adds a missing `KmsKeyId` attribute to `RestoreDBClusterToPointInTime` call. The reason for this change is to
ensure the CFN backend behavior is consistent across `CreateDBCluster`, `RestoreDBClusterFromSnapshot` and the aforementioned one.
=> [DBCluster] Add `KmsKeyId` to RestoreDBClusterToPointInTime

aws-rds-dbinstance/aws-rds-dbinstance.json, aws-rds-dbinstance/docs/README.md
This commit removes validation constraint for `Iops` attribute. The reason for this change is that some engine types do not support setting `iops` and customers set it to 0 to keep it consistent across all the templates in use. RDS API treats a 0-value as null, hence it is a valid parameter.
=> [DBInstance] Remove `Iops` validator

aws-rds-cfn-common/src/main/java/software/amazon/rds/common/util/IdentifierFactory.java, aws-rds-cfn-common/src/test/java/software/amazon/rds/common/util/IdentifierFactoryTest.java, aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/CreateHandler.java, aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/DeleteHandler.java, aws-rds-dbclusterparametergroup/src/main/java/software/amazon/rds/dbclusterparametergroup/BaseHandlerStd.java, aws-rds-dbclusterparametergroup/src/main/java/software/amazon/rds/dbclusterparametergroup/CreateHandler.java, aws-rds-dbclusterparametergroup/src/main/java/software/amazon/rds/dbclusterparametergroup/UpdateHandler.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/BaseHandlerStd.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/CreateHandler.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/DeleteHandler.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/CreateHandlerTest.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/DeleteHandlerTest.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/ListHandlerTest.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/UpdateHandlerTest.java, aws-rds-dbparametergroup/src/main/java/software/amazon/rds/dbparametergroup/BaseHandlerStd.java, aws-rds-dbparametergroup/src/main/java/software/amazon/rds/dbparametergroup/CreateHandler.java, aws-rds-dbsubnetgroup/src/main/java/software/amazon/rds/dbsubnetgroup/BaseHandlerStd.java, aws-rds-dbsubnetgroup/src/main/java/software/amazon/rds/dbsubnetgroup/CreateHandler.java, aws-rds-dbsubnetgroup/src/test/java/software/amazon/rds/dbsubnetgroup/AbstractTestBase.java, aws-rds-dbsubnetgroup/src/test/java/software/amazon/rds/dbsubnetgroup/CreateHandlerTest.java, aws-rds-dbsubnetgroup/src/test/java/software/amazon/rds/dbsubnetgroup/DeleteHandlerTest.java, aws-rds-dbsubnetgroup/src/test/java/software/amazon/rds/dbsubnetgroup/UpdateHandlerTest.java, aws-rds-eventsubscription/docs/README.md, aws-rds-eventsubscription/src/main/java/software/amazon/rds/eventsubscription/BaseHandlerStd.java, aws-rds-eventsubscription/src/main/java/software/amazon/rds/eventsubscription/CreateHandler.java, aws-rds-globalcluster/pom.xml, aws-rds-globalcluster/src/main/java/software/amazon/rds/globalcluster/BaseHandlerStd.java, aws-rds-globalcluster/src/main/java/software/amazon/rds/globalcluster/CreateHandler.java, aws-rds-optiongroup/src/main/java/software/amazon/rds/optiongroup/CreateHandler.java
This commit introduces a new util factory class called `IdentifierFactory`. The aim is to provide a generic and safe approach
for new identifier generation.
The current approach, which is adopted across all RDS CFN resources, uses cloudofrmation `IdentifierUtils` utility, which appears to be missing the double hyphens case and performs no null-safety checks on identifier components: stack id, logical resource identifier and request token.
The newly added util class generalizes the identifier generation approach and hides null-safety checks.
This commit affects all RDS CFN resources. Some areas of the code were changed due to an auto-formatting and auto-rearranges.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms …
=> [Common] Introduce `IdentifierFactory`

aws-rds-dbcluster/src/test/java/software/amazon/rds/dbcluster/CreateHandlerTest.java
This commit fixes a wrong unit test code assert import. The import was added by mistake. The library that was meant to be imported is `org.assertj.core.api.Assertions`. Due to a distinction in the CI/CD pipeline environments and imported suite, the pipeline experienced failures. This commit ensures the same Assertions library is used across all resources.
=> [DBCluster] Fix wrong Assert import

aws-rds-dbcluster/aws-rds-dbcluster.json
This commit eliminates a check for `MasterUsername` and `MasterPassword` if `ReplicationSourceIdentifier` is provided.
The reason for change is an incomplete validation schema that still requires the 2 aforementioned attributes to be provided despite that the replication source is set.
=> [DBCluster] Fix `ReplicationSourceIdentifier` validator

aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/BaseHandlerStd.java, aws-rds-dbcluster/src/test/java/software/amazon/rds/dbcluster/AbstractHandlerTest.java, aws-rds-dbcluster/src/test/java/software/amazon/rds/dbcluster/UpdateHandlerTest.java
This commit fixes an error in `DBClusterRole` comparison utility. It is being used by the `UpdateHandler` stabilization checker.
The faulty implementation compared the inner representation of `DBClusterRole` to the SDK version it received from `DescribeDBClusters` call. Upon a comparison, both `Arn` and `FeatureName` from the internal representation were safe-wrapped by `Optional` with a fallback to an empty string. The same null-safe wrapping was not performed for the SDK
representation, causing an empty string being compared to null. This comparison never succeeded, hence the handler timed out the resource stabilization.
This commit alters the comparison technique. It uses `Objects.equals` utility instead, which provides both null-safety and correctness in case any of the arguments is …
=> [DBCluster] Fix failing `AddRoleToDBCluster` stabilization

aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/BaseHandlerStd.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/UpdateHandler.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/UpdateHandlerTest.java
This commit fixes DBInstance UpdateHandler behavior when it is being invoked with `driftable=true` flag. This is a special case that occurs when CFN detects a resource drift and executes an additional series of stabilization loops. The entire idea behind this check is to see if the instance is required a reboot and ensuring it completes successfully.
In the current implementation reboot and stabilization loops are placed in a wrong order, causing the handler to wait forever upon a `pending-reboot` status and never reaching the point of the actual reboot. This fix changes this order and ensures the reboot is performed before the stabilization chain is started.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of …
=> [DBInstance] Fix resource drift stabilization

aws-rds-cfn-common/src/main/java/software/amazon/rds/common/handler/HandlerMethod.java, aws-rds-cfn-common/src/main/java/software/amazon/rds/common/handler/Tagging.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/CallbackContext.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/CreateHandler.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/AbstractHandlerTest.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/CreateHandlerTest.java
This commit changes the tagging soft fail algorithm. RDS resources implement tagging with a best-effort support: the handler code will attempt to create the resource with system tags only and then add the remaining tags separately. We are changing this approach to a 2-attempt run: initially the handler will attempt to create a resource with all tags, and if it fails, we will re-create the resource with system tags only (same as now) and attempt to invoke `AddTagsToResource` with the old soft-failing mechanism (silent failure).
This allows RDS to handle cases where customer FAS policies provide an additional condition enforcing presence of particular tags in `Create*` requests.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, …
=> [DBInstance] Soft fail tagging `AccessDenied` on create

aws-rds-dbclusterparametergroup/template.yml, aws-rds-dbparametergroup/template.yml
This commit updates `DBParameterGroup` and `DBClusterParameterGroup` lambda templates in order to increase max memory limit to 1024MB.
=> [DBParameterGroup] Bump lambda max memory constraint to 1024MB

aws-rds-dbsubnetgroup/aws-rds-dbsubnetgroup.json, aws-rds-dbsubnetgroup/src/main/java/software/amazon/rds/dbsubnetgroup/Translator.java
This commit changes DBSubnetGroup schema to tolerate duplicate `SubnetIds` and drop those duplicate in client request in order to not break current stacks with duplicate `SubnetIds`.
=> [DBSubnetGroup] Accept duplicate SubnetIds

aws-rds-dbsubnetgroup/src/main/java/software/amazon/rds/dbsubnetgroup/CreateHandler.java, aws-rds-dbsubnetgroup/src/test/java/software/amazon/rds/dbsubnetgroup/CreateHandlerTest.java
When customer specify stack IAM role with tag conditions. Create call will fail with `AccessDenied` exception because it contains only system tags and apply other tags by `AddTagsToResource`.
I.e: Customer created this stack with stack level tag `foo -> bar`
```
AWSTemplateFormatVersion: 2010-09-09
Description: RDS DBSubnetGroup Example Stack
Resources:
RDSDBSubnetGroup:
Type: AWS::RDS::DBSubnetGroup
Properties:
DBSubnetGroupDescription: "test_001 canary DBSubnetGroupDescription"
DBSubnetGroupName: CanaryDBSubnetGroupName
SubnetIds:
- Fn::ImportValue: CanarySubnetID1
- Fn::ImportValue: CanarySubnetID2
```
And assigned IAM Role to execute this stack
```
{
"Version": "2012-10-17",
"Statement": [
{
"Sid": "VisualEditor0",
"Effect": "Allow",
"Action": "rds:*", …
```
=> [DBSubnetGroup] Handle create call while stack having IAM role with tags

aws-rds-dbsubnetgroup/src/main/java/software/amazon/rds/dbsubnetgroup/BaseHandlerStd.java
Add DbSubnetGroupDoesNotCoverEnoughAZsException mapping
Example exception: `AwsErrorDetails(errorMessage=The DB subnet group doesn't meet Availability Zone (AZ) coverage requirement. Current AZ coverage: XX-XXXXX-1c. Add subnets to cover at least 2 AZs., errorCode=DBSubnetGroupDoesNotCoverEnoughAZs, serviceName=Rds)`
```
software.amazon.awssdk.services.rds.model.DbSubnetGroupDoesNotCoverEnoughAZsException: The DB subnet group doesn't meet Availability Zone (AZ) coverage requirement. Current AZ coverage: eu-central-1c. Add subnets to cover at least 2 AZs. (Service: Rds, Status Code: 400, Request ID: 172ed1c7-XXXX-4f97-XXXX-3d92e1a05a08)
at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleErrorResponse(CombinedResponseHandler.java:125)
at …
```
=> [DBSubnetGroup] Add DbSubnetGroupDoesNotCoverEnoughAZsException mapping

aws-rds-dbinstance/inputs/inputs_1_create.json, aws-rds-dbinstance/inputs/inputs_1_update.json, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/BaseHandlerStd.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/ReadHandler.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/UpdateHandler.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/CreateHandlerTest.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/ReadHandlerTest.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/UpdateHandlerTest.java
This commit alters ReadHandler behavior in a way it interprets a response from RDS API. RDS and CFN primary identifier contract differs significantly: whereas CFN treats primary identifiers as unconditionally immutable, RDS operates in a case-insensitive mode and coalesces all primary identifiers to lowercase. This contract-level disagreement causes an unpredictable behavior and triggers a drift detector immediately.
This commit instructs the read handler to restore the original `dbInstanceIdentifier` from `ResourceModel` in the resulting `ProgressEvent`. Having this in place allows RDS to keep operating in case-insensitive mode and return the original identifier matching the customer template value back to CFN.
By submitting this pull request, I confirm that you can use, modify, copy, …
=> [DBInstance] Restore original `dbInstanceIdentifier` case spelling

aws-rds-cfn-common/src/main/java/software/amazon/rds/common/error/ConditionalErrorStatus.java, aws-rds-cfn-common/src/main/java/software/amazon/rds/common/error/ErrorStatus.java, aws-rds-cfn-common/src/main/java/software/amazon/rds/common/error/PlainErrorRuleSet.java, aws-rds-cfn-common/src/test/java/software/amazon/rds/common/error/ErrorStatusTest.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/BaseHandlerStd.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/DeleteHandler.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/ListHandler.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/ReadHandler.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/DeleteHandlerTest.java
This commit changes `DBInstance` Delete ruleset. In particular, we instruct `DeleteHandler` to ignore `InvalidDBInstanceState` exceptions for the sake of handling an out-of-bounds delete. The motivation for the change is to achieve the backwards compatibility with the old implementation, which tolerates this resource state and simply continues to delete stabilization.
=> [DBInstance] Ignore `InvalidDBInstanceState` on Delete

aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/BaseHandlerStd.java, aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/ReadHandler.java, aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/UpdateHandler.java, aws-rds-dbcluster/src/test/java/software/amazon/rds/dbcluster/ReadHandlerTest.java
This commit modifies ReadHandler behavior so it restores the original `dbClusterIdentifier` case spelling. The motivation for this change is to fix CFN side effects caused by RDS coalescing all identifiers to lowercase. In particular, any mixed-case identified resource is a subject for an automatic replacement as an identifier is a replace-only modification for CFN.
This commit substitutes the observed (lowercased) identifier with the one provided in the template (original spelling).
=> [DBCluster] Restore original dbClusterIdentifier case spelling

aws-rds-dbcluster/aws-rds-dbcluster.json, aws-rds-dbcluster/resource-role.yaml
Update permissions for DB Cluster resource had a typo in it. Changed permissions to feature correct role.
=> [DBCluster] Fix typo in update permissions

aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/UpdateHandler.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/UpdateHandlerTest.java
This commit fixes a bug in UpdateHandler. Upon an update the handler checks if the instance vpc group set is empty and sets a default group in this case. This broke DBCluster instances as they must inherit the groups from the umbrella DBCluster.
=> [DBInstance] Fix default VPC group for cluster instances

aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/Translator.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/UpdateHandlerTest.java
This commit changes the way DBInstance UpdateHandler sets EngineVersion. Engine version change paths are primarily defined for upgrades, not for downgrades. It means that an attempt to set a lower engine version (which is the case upon a rollback after an attempt to upgrade the engine version) will be set for failure. This commit ensures the handler does not alter the engine version if a rollback is requested.
=> [DBInstance] Do not set EngineVersion upon a rollback

aws-rds-cfn-common/src/main/java/software/amazon/rds/common/error/ErrorCode.java, aws-rds-cfn-common/src/main/java/software/amazon/rds/common/handler/Commons.java
This commits adds another item in the `ErrorCode` enum: Throttling. It seems RDS API might return both `ThrottlingException` and `Throttling` as an errorCode when the number of requests exceeds the threshold. Adding this code should let the error handler to catch these cases and return a retriable error.
=> [Common] Add `Throttling` ErrorCode

aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/CallbackContext.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/CreateHandler.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/CreateHandlerTest.java
This commit fixes an issue in `CreateHandler`. When the handler soft-fails a `Create*` call containing all tags, it attempts to invoke the same method with system tags only. If this call succeeds, it enters a stabilization cycle. A `ProgressEvent` is re-entrant, meaning that any code that is not guarded by the special `ProgressEvent` sentinels would be re-executed every time a stabilizer returns an in-progress signal.
This effect had an impact on the `safeAddTags` method: whenever there was a downgrade to system-tags only, the original all-tags method was still invoked every time the system-tags only stabilizer returned an in-progress. This commit ensures that the all-tags `Create*` attempt will only fail once and won't be triggered upon a re-entrance.
By submitting this pull request, I …
=> [DBInstance] Fix repeating `Create*` call failures on tag softfail

aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/BaseHandlerStd.java, aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/ReadHandler.java, aws-rds-dbcluster/src/test/java/software/amazon/rds/dbcluster/UpdateHandlerTest.java
DBCluster was not using backoff delay in`AddAssociatedRoles`, and `RemoveAssociatedRoles` invocations and Read handler.
This request addresses this oversight.
=> [DBCluster] Use configured Backoff delay in all proxy invocations

aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/CallbackContext.java, aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/CreateHandler.java
This commit introduces no functional changes, but switches DBCluster `CreateHandler` from a locally-implemented `safeCreate` method to the library version from the commons package.
=> [DBCluster] Use `commons.Tagging.safeCreate`

aws-rds-dbclusterparametergroup/src/main/java/software/amazon/rds/dbclusterparametergroup/CallbackContext.java, aws-rds-dbclusterparametergroup/src/main/java/software/amazon/rds/dbclusterparametergroup/CreateHandler.java, aws-rds-dbclusterparametergroup/src/test/java/software/amazon/rds/dbclusterparametergroup/CreateHandlerTest.java
This commit introduces no functional changes, but switches DBClusterParameterGroup CreateHandler from a locally-implemented safeCreate method to the library version from the commons package.
=> [DBClusterParameterGroup] Use `commons.Tagging.safeCreate`

aws-rds-optiongroup/src/main/java/software/amazon/rds/optiongroup/CallbackContext.java, aws-rds-optiongroup/src/main/java/software/amazon/rds/optiongroup/CreateHandler.java
This commit introduces no functional changes, but switches OptionGroup CreateHandler from a locally-implemented safeCreate method to the library version from the commons package.
=> [OptionGroup] Use `commons.Tagging.safeCreate`

aws-rds-eventsubscription/src/main/java/software/amazon/rds/eventsubscription/CallbackContext.java, aws-rds-eventsubscription/src/main/java/software/amazon/rds/eventsubscription/CreateHandler.java
This commit introduces no functional changes, but switches EventSubscription CreateHandler from a locally-implemented safeCreate method to the library version from the commons package.
=> [EventSubscription] Use `commons.Tagging.safeCreate`

aws-rds-dbparametergroup/src/main/java/software/amazon/rds/dbparametergroup/CallbackContext.java, aws-rds-dbparametergroup/src/main/java/software/amazon/rds/dbparametergroup/CreateHandler.java
This commit introduces no functional changes, but switches DBParameterGroup CreateHandler from a locally-implemented safeCreate method to the library version from the commons package.
=> [DBParameterGroup] Use `commons.Tagging.safeCreate`

aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/CreateHandler.java
This commit cleans up safeCreate method in CreateHandler around the extraTags TagSet buildup. The current version was copied from the original allTags TagSet builder. It contains data type conversions that are no longer required at the stage when extraTags is being constructed.
=> [DBCluster] Clean up `safeCreate` tagset builder in `CreateHandler`

aws-rds-optiongroup/aws-rds-optiongroup.json, aws-rds-optiongroup/docs/README.md
This commit introduces a series of changes that are aiming to restore the
backwards compatibility in the resource implementation.
Removed strict enum-based Engine type validation: using an enum enforces a case sensitive validation and breaks existing clients.
Signed-off-by: Tieg O'Sullivan [tiegaws@amazon.com](mailto:tiegaws@amazon.com)
=> [OptionGroup] relax EngineName enum restrictions

aws-rds-dbparametergroup/src/main/java/software/amazon/rds/dbparametergroup/BaseHandlerStd.java, aws-rds-dbparametergroup/src/test/java/software/amazon/rds/dbparametergroup/CreateHandlerTest.java
This commit changes handling error that can be thrown during DescribeDBParameters and DescribeDefaultEngineParameters calls during pagination process.
=> [DBParameterGroup] Handling errors in DescribeDBParameters

aws-rds-dbsubnetgroup/src/main/java/software/amazon/rds/dbsubnetgroup/BaseHandlerStd.java, aws-rds-dbsubnetgroup/src/test/java/software/amazon/rds/dbsubnetgroup/CreateHandlerTest.java
This commit handles `InvalidSubnetException` that can happen when stack missing Subnet IDs
Example exception
```
software.amazon.awssdk.services.rds.model.InvalidSubnetException: Subnet IDs are required. (Service: Rds, Status Code: 400, Request ID: 9598d859-72ba-486a-xxxxxx-2a7a2624d690)
at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleErrorResponse(CombinedResponseHandler.java:125)
at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleResponse(CombinedResponseHandler.java:82)
at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:60)
at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:41)
at …
```
=> [DBSubnetGroup] Handle InvalidSubnetException Error

aws-rds-dbclusterparametergroup/src/main/java/software/amazon/rds/dbclusterparametergroup/BaseHandlerStd.java, aws-rds-dbclusterparametergroup/src/main/java/software/amazon/rds/dbclusterparametergroup/CreateHandler.java, aws-rds-dbclusterparametergroup/src/test/java/software/amazon/rds/dbclusterparametergroup/CreateHandlerTest.java
This commit alters the error handling ruleset that is being used in `waitForDbClustersStabilization`. The current implementation declares a stand-alone error rule set that is missing rule declarations for low-level issues like throttling and networking issues. This commit adds an alternative or-branch to DB_CLUSTERS_STABILIZATION_ERROR_RULE_SET so the aforementioned exceptions can be handled.
=> [DBClusterParameterGroup] Add default ruleset to DBCluster stabilization

aws-rds-dbclusterparametergroup/aws-rds-dbclusterparametergroup.json, aws-rds-dbclusterparametergroup/docs/tag.md, aws-rds-dbparametergroup/aws-rds-dbparametergroup.json, aws-rds-dbparametergroup/docs/tag.md
Make `Value` in tag definition optional. In that case value defaults to empty string
=> [DBParameterGroup][DBClusterParameterGroup] Make 'Value' in tag definition optional

aws-rds-dbcluster/aws-rds-dbcluster.json, aws-rds-dbcluster/docs/tag.md, aws-rds-dbclusterendpoint/aws-rds-dbclusterendpoint.json, aws-rds-dbclusterendpoint/docs/tag.md, aws-rds-dbinstance/aws-rds-dbinstance.json, aws-rds-dbinstance/docs/tag.md, aws-rds-dbsubnetgroup/aws-rds-dbsubnetgroup.json, aws-rds-dbsubnetgroup/docs/tag.md, aws-rds-eventsubscription/aws-rds-eventsubscription.json, aws-rds-eventsubscription/docs/tag.md, aws-rds-optiongroup/aws-rds-optiongroup.json, aws-rds-optiongroup/docs/tag.md
This pull request replicates changes from #229 to all resources. When tag value is not specified, value defaults to empty string.
=> [AllResources] Make value in tag definition optional

aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/BaseHandlerStd.java, aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/ReadHandler.java, aws-rds-dbcluster/src/test/java/software/amazon/rds/dbcluster/ReadHandlerTest.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/BaseHandlerStd.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/ReadHandler.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/CreateHandlerTest.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/ReadHandlerTest.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/UpdateHandlerTest.java
This commit is effectively a rollback for https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-rds/pull/196.
The approach used in this fix proved to be insufficient and hence the corresponding fix was made on a lower level of CFN instead.
=> [DBInstance][DBCluster] Remove restore original identifier

aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/BaseHandlerStd.java, aws-rds-dbcluster/src/test/java/software/amazon/rds/dbcluster/DeleteHandlerTest.java
This commit adds 2 more exception classes to the BaseHandler default error set. The reason for this change is an incomplete model error coverage by the resource handler. Sometimes a db cluster snapshot can either enter an unexpected state or the number of existing resources might exceed the quota. This commit instructs the resource handler to handle these 2 classes of exceptions.
=> [DBCluster] Handle SnapshotQuotaExceededFault and InvalidDbClusterSnapshotState

aws-rds-dbclusterparametergroup/src/main/java/software/amazon/rds/dbclusterparametergroup/BaseHandlerStd.java, aws-rds-dbclusterparametergroup/src/main/java/software/amazon/rds/dbclusterparametergroup/CallbackContext.java, aws-rds-dbclusterparametergroup/src/main/java/software/amazon/rds/dbclusterparametergroup/CreateHandler.java, aws-rds-dbclusterparametergroup/src/main/java/software/amazon/rds/dbclusterparametergroup/DeleteHandler.java, aws-rds-dbclusterparametergroup/src/main/java/software/amazon/rds/dbclusterparametergroup/ListHandler.java, aws-rds-dbclusterparametergroup/src/main/java/software/amazon/rds/dbclusterparametergroup/ReadHandler.java, aws-rds-dbclusterparametergroup/src/main/java/software/amazon/rds/dbclusterparametergroup/UpdateHandler.java, aws-rds-dbclusterparametergroup/src/test/java/software/amazon/rds/dbclusterparametergroup/AbstractTestBase.java, aws-rds-dbclusterparametergroup/src/test/java/software/amazon/rds/dbclusterparametergroup/CreateHandlerTest.java, aws-rds-dbclusterparametergroup/src/test/java/software/amazon/rds/dbclusterparametergroup/DeleteHandlerTest.java, aws-rds-dbclusterparametergroup/src/test/java/software/amazon/rds/dbclusterparametergroup/ListHandlerTest.java, aws-rds-dbclusterparametergroup/src/test/java/software/amazon/rds/dbclusterparametergroup/ReadHandlerTest.java, aws-rds-dbclusterparametergroup/src/test/java/software/amazon/rds/dbclusterparametergroup/UpdateHandlerTest.java
This commit fixes an issue with the final stage of `applyParameters`.
Once the parameters have been applied, the handler code stabilizes on the list of `DBCluster` objects that might depend on this `DBClusterParameterGroup`. This stabilization is being short-circuited by a flag used for unit testing purposes: a re-entrant chain invocation skips the stabilization and reports an update complete status. Any upcoming `ModifyDBCluster` calls on a dependant cluster object will cause a `DB cluster isn't available for modification with status modifying` API rejection.
This commit fixes the eager flag set (set too early).
Signed-off-by: Oleg Sidorov …
=> [DBClusterParameterGroup] Fix premature DBCluster stabilization

aws-rds-dbclusterparametergroup/src/main/java/software/amazon/rds/dbclusterparametergroup/UpdateHandler.java, aws-rds-dbclusterparametergroup/src/test/java/software/amazon/rds/dbclusterparametergroup/UpdateHandlerTest.java
This commit fixes unnecessary `AddTagsToResource` and `RemoveTagsFromResource` requests that occur in `UpdateHandler` when a cluster parameter group is being modified. The error happens on re-entrance when the handler enters DBCluster stabilization cycle. Even though adding already existing tags and removing non-existing ones is a no-op, RDS API can probablistically spawn a DBCluster update cycle and this can break a following ModifyDBCluster invocation.
=> [DBClusterParameterGroup] Fix repeating tag updates in UpdateHandler

aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/BaseHandlerStd.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/CallbackContext.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/CreateHandler.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/UpdateHandler.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/AbstractHandlerTest.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/BaseHandlerStdTest.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/CreateHandlerTest.java
This commit reimplements the current stabilization logic used in CreateHandler and UpdateHandler. The existing implementation is "shallow": it only checks the db instance status and ensures it reaches up "available" state.
The actual status is composite and is spread across multiple attributes. In particular, a complete availability status is defined as:
- db instance status is "available"
- all replication status info entries are in "replicating" status
- none of db parameter group entries is in "applying" status
- pending modified values is empty
- all vpc security groups are in "active" status
- all domain membership entries are either in "joined" or "kerberos-enabled" statuses
- promotion tier is updated
This commit alters the stabilization logic so it conforms to the contract above. …
=> [DBInstance] Rework stabilization

aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/BaseHandlerStdTest.java
This commit removes usage of junit.framework.Assert accidentally added by https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-rds/pull/243
The assertion framework in use is org.assertj.core.api.Assertions.
=> [DBInstance] Remove junit.framework.Assert

aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/Translator.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/TranslatorTest.java
Not all engines support setting DBParameterGroup on creation of read replicas. Instead, we set read replicas on subsequent modify request.
=> [DBInstance] Do not set DBParameterGroup on create of read replica

aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/BaseHandlerStd.java, aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/CreateHandler.java, aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/UpdateHandler.java
This PR reconciles the difference between stabilization timeout in old and new implementation of DBCluster. Old implementation used 36h timeout.
=> [DBCluster] Set timeout to 36h for Create and Update handlers to match old implementation

aws-rds-dbcluster/aws-rds-dbcluster.json, aws-rds-dbcluster/resource-role.yaml, aws-rds-dbinstance/aws-rds-dbinstance.json, aws-rds-dbinstance/resource-role.yaml
In the recent changes the timeout for Create and Update stabilization for `DBInstance` and `DBCluster` resources was set to 36 hours, however the handler timeout was not updated to match. This PR addresses this oversight.
=> [DBInstance][DBCluster] set timeout for Create and Update handlers to 36 hours

aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/Configuration.java, aws-rds-dbcluster/src/test/java/software/amazon/rds/dbcluster/ConfigurationTest.java, aws-rds-dbclusterparametergroup/src/main/java/software/amazon/rds/dbclusterparametergroup/Configuration.java, aws-rds-dbclusterparametergroup/src/test/java/software/amazon/rds/dbclusterparametergroup/ConfigurationTest.java, aws-rds-dbsubnetgroup/src/main/java/software/amazon/rds/dbsubnetgroup/Configuration.java, aws-rds-dbsubnetgroup/src/test/java/software/amazon/rds/dbsubnetgroup/ConfigurationTest.java, aws-rds-eventsubscription/src/main/java/software/amazon/rds/eventsubscription/Configuration.java, aws-rds-eventsubscription/src/test/java/software/amazon/rds/eventsubscription/ConfigurationTest.java, aws-rds-optiongroup/src/main/java/software/amazon/rds/optiongroup/Configuration.java, aws-rds-optiongroup/src/test/java/software/amazon/rds/optiongroup/ConfigurationTest.java
This commit is a follow-up on https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-rds/pull/230.
It fixes a bug in `Configuration` class that failed to merge tag maps with null-values.
Affected resources:
- AWS::RDS::DBCluster
- AWS::RDS::DBClusterParameterGroup
- AWS::RDS::DBSubnetGroup
- AWS::RDS::EventSubscription
- AWS::RDS::OptionGroup
=> [DBClusterParameterGroup+4] Handle tags with empty value

aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/BaseHandlerStd.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/CreateHandler.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/DBInstanceStatus.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/AbstractHandlerTest.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/BaseHandlerStdTest.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/UpdateHandlerTest.java
This commit introduces a distinction between stabilization processes after create and update. The change is introduced for the sake of a complete logic parity with the historical implementation. In particular, the post-update stabilization is:
- DBInstance status is `available`
- DBParameterGroup status is `in-sync`
- OptionGroup status is `in-sync`
- if DBInstance is a member of a DBCluster:
- DBClusterParameterGroup is `in-sync`
Both stabilizers perform an additional assertion on DBInstance status. The assertion code performs an early process interruption if DBInstance enters one of the following statuses:
- failed
- incompatible-restore
- incompatible-network
- incompatible-parameters
- inaccessible-encryption-credentials
In this case the handler will throw a …
=> [DBInstance] Change stabilization logic on update

aws-rds-dbcluster/aws-rds-dbcluster.json, aws-rds-dbclusterendpoint/aws-rds-dbclusterendpoint.json, aws-rds-dbclusterparametergroup/aws-rds-dbclusterparametergroup.json, aws-rds-dbinstance/aws-rds-dbinstance.json, aws-rds-dbparametergroup/aws-rds-dbparametergroup.json, aws-rds-dbsubnetgroup/aws-rds-dbsubnetgroup.json, aws-rds-eventsubscription/aws-rds-eventsubscription.json, aws-rds-optiongroup/aws-rds-optiongroup.json
Drift detection falsely detects drift when the spelling of case-insensitive identifiers have been changed. To prevent that, we lowercase relevant identifiers.
=> [All resources] Coalesce primary identifiers to lowercase to prevent false drift detection

aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/BaseHandlerStd.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/CreateHandler.java
This PR is a follow-up on the change introduced in https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-rds/pull/251.
The initial change introduced a distinction between create and update stabilization logic. This distinction was not precise enough: a DBInstance can enter pending-reboot state after an update and the existing logic would block as it requires an in-sync state.
This commit introduces a change to the stabilization logic. Any mutating change would be stabilized with the same logic (including creates and updates) and post-reboot gets its own stabilizer that would ensure the minimal set of availability flags and assert an in-sync (rather than "anything but applying") status.
By submitting this pull request, I confirm that you can use, modify, copy, and …
=> [DBInstance] Unify stabilization for create and update

aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/BaseHandlerStd.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/CreateHandlerTest.java
This change adds `DbClusterNotFoundException` entry to the `DEFAULT_DB_INSTANCE_ERROR_RULE_SET`. The motivation for this change is to properly map a case when the source db cluster identifier points to a non-existing resource and RDS service returns a corresponding 404 error.
=> [DBInstance] Handle `DbClusterNotFoundException`

aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/BaseHandlerStd.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/CreateHandlerTest.java
This commit fixes the default DBInstance error rule set. `CreateDBInstance` and `ModifyDBInstance` API calls might return an `OptionGroupNotFoundFault`. Currently an `InternalFault` status is returned.
=> [DBInstance] Handle OptionGroupNotFoundException

aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/BaseHandlerStd.java, aws-rds-dbcluster/src/test/java/software/amazon/rds/dbcluster/CreateHandlerTest.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/BaseHandlerStd.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/CreateHandlerTest.java
This PR addresses an oversight is Error Rule Set that was interpreting DomainNotFoundException as Internal Error. It is now being interpreted as NotFound.
=> [DBInstance][DBCluster] Return NotFound status when AD domain is not found

aws-rds-optiongroup/src/main/java/software/amazon/rds/optiongroup/OptionVersion.java, aws-rds-optiongroup/src/test/java/software/amazon/rds/optiongroup/UpdateHandlerTest.java
This pr aims to add defensive statement for customers who are not using Option versioning for their option groups
=> [OptionGroup] Add defensive statement for a customer not using option versioning

aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/util/ImmutabilityHelper.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/UpdateHandlerTest.java
This PR relaxes the restrictions on PerformanceInsightsKMSKeyId, allowing to update it if it was not previously specified.
=> [DBInstance] Allow updates of PerformanceInsightsKMSKeyId if it was not previously specified

aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/Translator.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/CreateHandlerTest.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/UpdateHandlerTest.java
This commit changes the way Translator code sets `vpcSecurityGroupIds` attribute on the following requests:
- `CreateDBInstance`
- `CreateDBInstanceReadReplica`
- `RestoreDBIntanceFromDBSnapshot`
- `ModifyDBInstance`
The motivation for this change is to ensure no explicit empty list is being set as in this case RDS API won't recognize it as a no-change but will interpret it as an explicitly empty collection and fail if the configuration is incorrect.
=> [DBInstance] Unset empty `vpcSecurityGroupIds`

aws-rds-dbinstance/aws-rds-dbinstance.json, aws-rds-dbinstance/docs/README.md
This commit adds a numeric validator on `AllocatedStorage` attribute. The motivation for this change is to ensure the value looks like a valid numeric argument and could be parsed into an Integer upon a request construction.
=> [DBInstance] Fix `AllocatedStorage` validation

aws-rds-dbinstance/aws-rds-dbinstance.json, aws-rds-dbinstance/docs/README.md
This commit removes schema-based validators from DBInstance resource definition. The motivation for this change is to eliminate inter-dependencies and validation logic inconsistency between CFN resources. At the moment, DBInstance performs additional validations on the reference-type properties.
Reference-type properties are effectively borrowed attributes: DBInstance does not own these propoerties (they are effectively pointers on external resources). With this change we are delegating the reference-type validation to the corresponding owning resources or to the RDS API if the resource was created out of CFN scope.
Having this change in place would allow us to consolidate the validation logic in the owning resources and eliminate export issues caused by legacy resources that would no …
=> [DBInstance] Drop reference-type schema validators

aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/BaseHandlerStd.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/CreateHandler.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/DeleteHandler.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/Translator.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/util/ResourceModelHelper.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/util/UpdateAfterCreateHelper.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/TranslatorTest.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/util/ResourceModelHelperTest.java
This PR addresses the issue of long storage optimization step when the DBInstance is being restored from snapshot with non-default storage type 
=> [DBInstance] Set storage type on restore from snapshot with subsequent modify call

aws-rds-dbinstance/aws-rds-dbinstance.json, aws-rds-dbinstance/docs/README.md, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/util/ImmutabilityHelper.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/util/ImmutabilityHelperTest.java
This PR allows the DBInstance to be upgraded to MultiAZ instance without replacement in case when the customer does not explicitly specifies Availability Zone.
=> [DBInstance] Allow upgrading instance to MultipleAZ without replacement.

aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/Translator.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/CreateHandlerTest.java
This commit updates `ModifyDBInstance` request construction after create. In particular, `EngineVersion` was missing from the consecutive modify-after-create request, causing instances restored from snapshots to have an inconsistent `engineVersion` with the template data.
=> [DBInstance] Set `engineVersion` after restoring an instance from a snapshot

aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/DeleteHandler.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/DeleteHandlerTest.java
This commit enforces the final snapshot creation on DBInstance delete in case the request contains no data on whether a final snapshot creation is requested or not. The reason for this change is the referential value type returned by `ResourceHandlerRequest.getSnapshotRequested()`. The return value is a Boolean, meaning it can be yes/no/null(no data). This commit addresses the latter case where the invocation request is neither asking for a final snapshot nor disclaiming it.
=> [DBInstance] Enforce final snapshot if not explicitly requested

aws-rds-dbinstance/aws-rds-dbinstance.json, aws-rds-dbinstance/docs/README.md
This PR addresses an error in the schema of DBInstance. Where the regex for this resource doesn't count hyphens in an accurate way. Leading to a scenario where hyphens aren't counted. This becomes a problem if the additional hyphens takes the total length of the identifier over 63 characters long.
=> [DBInstance] updated schema to include min and max length

aws-rds-dbinstance/aws-rds-dbinstance.json, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/DeleteHandler.java
DBInstance delete workflow can take very long time. Older implementation of CloudFormation used 36h timeout. This PR applies the same timeout to delete handler.
=> [DBInstance] Set DBInstance DeleteHandler stabilization time to match older implementation

aws-rds-cfn-common/src/main/java/software/amazon/rds/common/error/ErrorCode.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/BaseHandlerStd.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/CreateHandlerTest.java
This commit adds a new ErrorCode: `DBClusterNotFoundFault`. RDS API can communication this error using 2 distinct classes of errors:
- `DbClusterNotFoundException` (native SDK-shipped exception class)
- `AwsSdkException` with a code `DBClusterNotFoundFault`.
Prior to this change the handler interpreted `DBClusterNotFoundFault` error codes as a `GeneralServiceException`.
=> [DBInstance] Handle DBClusterNotFoundFault service error code

aws-rds-dbcluster/inputs/inputs_1_create.json, aws-rds-dbcluster/inputs/inputs_1_update.json
Contract tests for DBCluster are using aurora engine, which defaults to mysql 5.6 which soon will reach EOL. This PR upgrades contract tests to use at least aurora-mysql 5.7 engine version.
=> [DBCluster] update contract tests to use newer version of aurora-mysql engine

aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/BaseHandlerStd.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/CreateHandler.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/DeleteHandler.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/ListHandler.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/ReadHandler.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/Translator.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/UpdateHandler.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/request/RequestValidationException.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/request/ValidatedRequest.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/BaseHandlerStdTest.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/TranslatorTest.java
This commit adds a request validation layer to the handler execution chain. The motivation is to extend the schema-based validation with a range of more flexible and more dynamic validation methods.
The change introduces a new class `ValidatedRequest` that extends `ResourceHandlerRequest` with 0 overloading: it is here to distinguish a validated request from a raw one.
The change adds a new validation on the `sourceRegion` attribute. If a provided region is incorrect, the validation will refuse such a request well before it reaches the SDK endpoint connection initialization.
=> [DBInstance] Add ResourceHandlerRequest validation

aws-rds-cfn-common/src/main/java/software/amazon/rds/common/error/ErrorCode.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/BaseHandlerStd.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/util/ImmutabilityHelper.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/CreateHandlerTest.java
This commit adds a definition for `StorageTypeNotSupportedFault` error code to DBInstance default error set. It could be returned by RDS API in case when a storage type is not supported by the engine or disabled.
=> [DBInstance] Handle StorageTypeNotSupportedFault

aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/Translator.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/DeleteHandlerTest.java
This commit adds `DeleteAutomatedBackups` attribute to the `DeleteDBInstance` request constructor. The current version is missing this parameter so no automated backup deletion policy is set.
=> [DBInstance] Pass DeleteAutomatedBackups parameter

aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/BaseHandlerStdTest.java
This commit fixes an issue in BaseHandlerTest. In particular, `assertThatNoException` is being replaced by `assertThatCode.doesNotThrowAnyException`. The motivation for this change is to avoid locking on the edge-version of AssertJ and stick to the older API.
=> [DBInstance] Remove edge-version AssertJ API use

aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/BaseHandlerStd.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/CallbackContext.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/Translator.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/UpdateHandler.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/AbstractHandlerTest.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/UpdateHandlerTest.java
This PR enables the possibility of recovery from `storage-full` state. In order to do so, Update handler attempts to perform `AllocatedSize` only update on the instance. 
=> [DBInstance] Enable recovery from storage-full state

aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/BaseHandlerStd.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/CreateHandlerTest.java
This commit adds `DBSubnetGroupDoesNotCoverEnoughAZs` error class as a known invalid request case.
=> [DBInstance] Handle DBSubnetGroupDoesNotCoverEnoughAZs

aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/BaseHandlerStd.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/AbstractHandlerTest.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/CreateHandlerTest.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/DeleteHandlerTest.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/UpdateHandlerTest.java
This commit adds handling of `InvalidSubnetException` as a general service exception. The status is chosen to be terminal as it requires an customer interaction.
=> [DBInstance] Handle `InvalidSubnetException`

aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/BaseHandlerStd.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/CreateHandlerTest.java
This PR adds AuthoriazationNotFound to the list of supported exceptions.
This exception can be raised when the specified CIDR IP range or Amazon EC2 security group might not be authorized for the specified DB security group. Or, RDS might not be authorized to perform necessary actions using IAM on your behalf.
=> [DBInstance] Add AuthorizationNotFoundException to the list of expected exceptions

aws-rds-dbcluster/aws-rds-dbcluster.json, aws-rds-dbcluster/resource-role.yaml
This commit adds a missing `rds:DescribeDBSubnetGroups` FAS policy to the list of the requested permissions for Update requests.
=> [DBCluster] Add `rds:DescribeDBSubnetGroups` to permissions

aws-rds-dbcluster/aws-rds-dbcluster.json, aws-rds-dbcluster/resource-role.yaml
This commit adds `ec2:DescribeSecurityGroups` FAS policy to the list of the requested permissions.
The initial API addition was performed in https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-rds/pull/254, but the schema policy was missing.
=> [DBCluster] Add `ec2:DescribeSecurityGroups` permission

aws-rds-dbinstance/aws-rds-dbinstance.json
This PR removes EngineVersion from the list of Conditionally Create-Only properties as there are currently no conditions when the change of EngineVersion will cause replacement. 
=> [DBInstace] Remove EngineVersion from conditional create only properties

aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/BaseHandlerStd.java, aws-rds-dbcluster/src/test/java/software/amazon/rds/dbcluster/CreateHandlerTest.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/BaseHandlerStd.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/CreateHandlerTest.java
This commit adds `StorageTypeNotSupportedException` to the InvalidRequest mapping. A recent attempt to address this exception was insufficient (https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-rds/pull/278) as both `StorageTypeNotSupportedException` and `StorageTypeNotSupportedFault` could be returned by the RDS API depending on the implementation.
This commit adds both error class and the error code to the default error rulesets of DBInstance and DBCluster.
=> [DBInstance][DBCluster] Handle StorageTypeNotSupportedException

aws-rds-dbclusterparametergroup/src/main/java/software/amazon/rds/dbclusterparametergroup/Translator.java
This commit adds an additional filtering to `DescribeDBClusterParameters`. Having it in-place reduces the page depth of the cluster parameter fetch. The amount of parameters to be fetched is limited to the parameters that are directly enumerated in the `ResourceModel`.
=> [DBClusterParameterGroup] Filtered `DescribeDBClusterParameters`

aws-rds-dbparametergroup/src/main/java/software/amazon/rds/dbparametergroup/BaseHandlerStd.java
This change attempts to address an incorrect key for a dependent parameter. From "character_set" (as displayed in rds error messages) to "character_set_server" (as defined in a customer's template)
=> [DBParameterGroup] Update to dependency map to include correct parameter key 'character_set_server'

aws-rds-cfn-common/src/main/java/software/amazon/rds/common/test/AbstractTestBase.java, aws-rds-cfn-common/src/main/java/software/amazon/rds/common/util/ParameterGrouper.java, aws-rds-cfn-common/src/test/java/software/amazon/rds/common/util/ParameterGrouperTest.java, aws-rds-dbclusterparametergroup/src/main/java/software/amazon/rds/dbclusterparametergroup/BaseHandlerStd.java, aws-rds-dbparametergroup/src/main/java/software/amazon/rds/dbparametergroup/BaseHandlerStd.java
This request supersedes #302
This pr duplicate the logic used by DBParameterGroup to group dependent parameters for DBClusterParameterGroup.
=> [DBClusterParameterGroup] Add grouping support for DBClusterParameterGroup

aws-rds-dbclusterparametergroup/aws-rds-dbclusterparametergroup.json, aws-rds-dbclusterparametergroup/resource-role.yaml, aws-rds-dbclusterparametergroup/src/main/java/software/amazon/rds/dbclusterparametergroup/BaseHandlerStd.java
DBClusterParameterGroup was not using backoff config during stabilisation, this PR fixes this oversight. In addition, timeout has been adjusted to be consistent with the backoff.
=> [DBClusterParameterGroup] Stabilisation timeouts

aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/Translator.java
We identified a regression in DBCluster where the dbClusterParameterGroupName was not included as part of the initial RestoreDbClusterFromSnapshot call. This for the most part is fine as the parameter is added in the follow up call to modify the cluster.
This causes a consistency problem that is sometimes enforced by RDS. Like in the case of:  
`lower_case_table_names setting isn't supported for MySQL 8.0 and higher versions`  
Where a customer has taken a snapshot of a cluster with a custom CPG and a custom value for `lower_case_table_names`. Then when they try to restore the cluster with the same custom CPG, the CPG isn't included in the restore call, so the default CPG is used with a different value for `lower_case_table_names`. Throwing the above error.
Adding this code change will …
=> [DBCluster] add dbClusterParameterGroupName to RestoreDbClusterFromSnapshot

aws-rds-dbcluster/aws-rds-dbcluster.json, aws-rds-dbcluster/resource-role.yaml
Add rds:DescribeGlobalClusters permission as we are using this call while stabilzation after removing cluster from GlobalCluster
=> [DBCluster] Add rds:DescribeGlobalClusters permission

aws-rds-dbinstance/aws-rds-dbinstance.json, aws-rds-dbinstance/docs/README.md
Setting CustomIAMInstanceProfile is only supported on creation. This CR addresses oversight in original implementation.
=> [DBInstance] Correct CustomIAMInstanceProfile update strategy

aws-rds-dbcluster/aws-rds-dbcluster.json, aws-rds-dbcluster/docs/README.md, aws-rds-dbcluster/docs/serverlessv2scalingconfiguration.md, aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/Translator.java, aws-rds-dbcluster/src/test/java/software/amazon/rds/dbcluster/AbstractHandlerTest.java, aws-rds-dbcluster/src/test/java/software/amazon/rds/dbcluster/CreateHandlerTest.java, aws-rds-dbcluster/src/test/java/software/amazon/rds/dbcluster/UpdateHandlerTest.java
This commit adds a new attribute to DBCluter resource definition: `ServerlessV2ScalingConfiguration`. The motivation for this change is to catch up on the existing serverless configuration feature exposed by the SDK and CLI tool.
The teamplate structure is expected in the following format:
```yaml
ServerlessV2ScalingConfiguration:
MaxCapacity: <number>
MinCapacity: <number>
```
The attribute itself is optional.
Documentation:
- https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/aurora-serverless-v2.html
- https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_ServerlessV2ScalingConfiguration.html
Signed-off-by: Oleg Sidorov …
=> [DBCluster] Implement ServerlessV2ScalingConfiguration

aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/BaseHandlerStd.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/UpdateHandler.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/status/DBInstanceStatus.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/status/DBParameterGroupStatus.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/status/DomainMembershipStatus.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/status/OptionGroupStatus.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/status/ReadReplicaStatus.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/status/Status.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/status/TerminableStatus.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/status/VPCSecurityGroupStatus.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/CreateHandlerTest.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/UpdateHandlerTest.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/status/DBInstanceStatusTest.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/status/DBParameterGroupStatusTest.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/status/DomainMembershipStatusTest.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/status/OptionGroupStatusTest.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/status/ReadReplicaStatusTest.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/status/VPCSecurityGroupStatusTest.java
This commits performs a shallow refactoring of the status tracking layer which was implemented as a trivial set of string constants. `DBInstanceStatus` was the first case where we had to attach some additional meta-information to the status (terminal status flag).
Given our ultimate aim to let the stack expose unrecoverable problems as soon as possible, we are adding the same bit of information (terminal status flag) to `OptionGroupStatus`. This move motivates an introduction of a new inheritance chain.
Firstly, we introduce a `Status` interface which defines a minimalistic API for status-like enums. Whereas enums is a great way of handling discrete values, java adds some limitations on using the actual inheritance on these classes, hence we favor interfaces.
The second family grid or …
=> [DBInstance] Move status definitions to enums

aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/CreateHandler.java, aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/ModelAdapter.java, aws-rds-dbcluster/src/test/java/software/amazon/rds/dbcluster/AbstractHandlerTest.java, aws-rds-dbcluster/src/test/java/software/amazon/rds/dbcluster/CreateHandlerTest.java
This commits fixes the create handler behavior in case a port value was not provided. The default value for this port is `3306` for Aurora and `5432` for Aurora Postgres.
Fixes #48.
Fixes https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/281.
=> [DBCluster] Set default port for aurora-postgresql to `5432`

aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/Translator.java, aws-rds-dbcluster/src/test/java/software/amazon/rds/dbcluster/UpdateHandlerTest.java
This commit changes `applyImmediately` flag from a conditionaly-set to always-set upon a modify-db-cluster request. The motivation for this change is to ensure all pending actions are applied within the current modification cycle rather than waiting until the next maintenance window goes off.
=> [DBCluster] Apply modifications immediately

aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/BaseHandlerStd.java, aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/UpdateHandler.java, aws-rds-dbcluster/src/test/java/software/amazon/rds/dbcluster/AbstractHandlerTest.java, aws-rds-dbcluster/src/test/java/software/amazon/rds/dbcluster/UpdateHandlerTest.java
Change the unconditional way we update associated roles in DBCluster to only update the difference in roles between previous state and desired resource.
=> [DBCluster] Only update difference in associated roles.

aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/BaseHandlerStd.java, aws-rds-dbcluster/src/test/java/software/amazon/rds/dbcluster/UpdateHandlerTest.java
This commit adds an additional condition to the DBCluster stabilization logic: apart from checking that the cluster has achieved an Available state, it also checks there are no pending actions scheduled for an immediate execution.
The motivation for this change is the RDS API specifics: whereas some attributes are being applied immediately, the rest could be scheduled up for a delayed execution and picked up as soon as possible. This is the case for the following attributes:
- `masterUserPassword`
- `iamDatabaseAuthenticationEnabled`
- `engineVersion`
This commit ensures the handler will inspect `pendingActions` before moving on.
Fixes #56. …
=> [DBCluster] Stabilize on pending actions

aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/Translator.java, aws-rds-dbcluster/src/test/java/software/amazon/rds/dbcluster/CreateHandlerTest.java
This commit modifies `RestoreDBClusterToPointInTime` request construction. In particular, `VPCSecurityGroupIds` parameter is being passed from the desired resource state. In this case one can restore a customer with a reference to the same security group set as the original cluster.
Fixes #15.
Fixes https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/336.
=> [DBCluster] Pass `VPCSecirutyGroups` to `RestoreDBClsuterToPointInTime`

aws-rds-dbcluster/aws-rds-dbcluster.json, aws-rds-dbcluster/docs/scalingconfiguration.md, aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/Translator.java
This PR adds support for TimeoutAction for ServerlessV1: https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_ScalingConfiguration.html
=> [DBCluster][ServerlessV1] Add support for TimeoutAction

aws-rds-dbclusterparametergroup/aws-rds-dbclusterparametergroup.json, aws-rds-dbclusterparametergroup/docs/README.md, aws-rds-dbparametergroup/aws-rds-dbparametergroup.json, aws-rds-dbparametergroup/docs/README.md, aws-rds-optiongroup/aws-rds-optiongroup.json, aws-rds-optiongroup/docs/README.md, aws-rds-optiongroup/src/main/java/software/amazon/rds/optiongroup/CreateHandler.java, aws-rds-optiongroup/src/test/java/software/amazon/rds/optiongroup/CreateHandlerTest.java
This PR makes primary identifiers for OptionGroup, DBParameterGroup and DBClusterParameterGroup resources CreateOnly instead of readonly. This will allow customers to specify those parameters on creation
Fixes https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/212.
=> [OptionGroup][DBParameterGroup][DBClusterParameterGroup] Make primary identifers for several resources CreateOnly

aws-rds-dbinstance/aws-rds-dbinstance.json, aws-rds-dbinstance/docs/README.md, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/CallbackContext.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/Translator.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/UpdateHandler.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/util/ImmutabilityHelper.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/UpdateHandlerTest.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/util/ImmutabilityHelperTest.java
This PR adds support for ReadReplica promotion. When customer updates DBInstance read replica which previously had SourceDBInstanceIdentifier set to no longer having one, promoteReadReplica API will be used rather than re-creation of a DBInstance will be triggered.
Fixes https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/67.
=> [DBInstance] Add support for read replica promotion

aws-rds-cfn-common/src/main/java/software/amazon/rds/common/printer/FilteredJsonPrinter.java, aws-rds-cfn-common/src/main/java/software/amazon/rds/common/status/Status.java, aws-rds-cfn-common/src/main/java/software/amazon/rds/common/status/TerminableStatus.java, aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/BaseHandlerStd.java, aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/DBClusterStatus.java, aws-rds-dbcluster/src/test/java/software/amazon/rds/dbcluster/CreateHandlerTest.java, aws-rds-dbcluster/src/test/java/software/amazon/rds/dbcluster/DBClusterStatusTest.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/status/DBInstanceStatus.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/status/DBParameterGroupStatus.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/status/DomainMembershipStatus.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/status/OptionGroupStatus.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/status/ReadReplicaStatus.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/status/VPCSecurityGroupStatus.java
This PR allows for DBCluster to fail early when encountering a terminal status during stabilization
=> [DBCluster] Fail early when encountering a terminal DBCluster status

aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/EngineMode.java, aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/ModelAdapter.java, aws-rds-dbcluster/src/test/java/software/amazon/rds/dbcluster/CreateHandlerTest.java, aws-rds-dbinstance/resource-role.yaml
This commit is a follow-up on https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-rds/pull/324.
As per the last change, the default port was set to 5432 on all aurora-postgresql engine versions. According to the documentation, provisioned engine versions should still default to 3306 no matter what engine version was set. This commit introduces a more granular default engine port mapping.
Refs https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/281.
=> [DBCluster] Set default port for aurora-postgresql on serverless only

aws-rds-dbclusterparametergroup/src/main/java/software/amazon/rds/dbclusterparametergroup/BaseHandlerStd.java, aws-rds-dbclusterparametergroup/src/main/java/software/amazon/rds/dbclusterparametergroup/Translator.java, aws-rds-dbclusterparametergroup/src/test/java/software/amazon/rds/dbclusterparametergroup/CreateHandlerTest.java, aws-rds-dbclusterparametergroup/src/test/java/software/amazon/rds/dbclusterparametergroup/TranslatorTest.java
This commit is a follow-up on https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-rds/pull/337.
The motivation for the change is to eliminate a describe parameters call completely if the model parameter set is empty. Under the hood, this change is dictated by the fact that an empty parameter set is an invalid request from RDS API's perspective. In this case we should choose between these 2 options:
* set no filters of the param set is empty
* do not describe current parameters at all (as the upcoming validation would cross-match an empty parameter set against a presumably empty default parameter set, hence it is a no-op).
This commit is a move from point 1 to point 2.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …
=> [DBClusterParameterGroup] Do not describe parameters if empty

aws-rds-cfn-common/src/main/java/software/amazon/rds/common/util/DifferenceUtils.java, aws-rds-cfn-common/src/test/java/software/amazon/rds/common/util/DifferenceUtilsTest.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/CreateHandlerTest.java
This PR fixes a regression introduced by #323 for some DBInstance Create scenarios. When DBInstance requires update after create - read replica creation, restore from snapshot, or CACertificate is applied, and an empty vpcSecurityGroupIds list is provided and the instance is a member of DBCluster, ModifyDBInstance call will no longer fail.
=> [DBInstance] Fix DBInstance Empty vpcSecurityGroupIds create-with-update scenario

aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/CreateHandler.java, aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/EngineMode.java, aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/Translator.java, aws-rds-dbcluster/src/test/java/software/amazon/rds/dbcluster/CreateHandlerTest.java
This commit continues the conditional modify-db-cluster attribute set approach applied in DBInstance. In particular, setting `port` attribute is now conditional as RDS API is quite inconsistent in accepting the same-value parameters: some engines/engine modes would accept it just fine if it is a no-change set, but some would reject agressively.
=> [DBCluster] Set port conditionally on modify after create

aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/ModelAdapter.java, aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/UpdateHandler.java, aws-rds-dbcluster/src/test/java/software/amazon/rds/dbcluster/CreateHandlerTest.java, aws-rds-dbcluster/src/test/java/software/amazon/rds/dbcluster/UpdateHandlerTest.java
This commit ensures the `UpdateHandler` unsets the default port on update. The motivation for this change is to eliminate cases where RDS API would reject a modify request due to a non-null port value. This behavior is engine-specific hence setting port to null upon a no-change seems to be the one-size-fits all approach.
This commit is a follow-up on a change we delivered earlier: https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-rds/pull/343
=> [DBCluster] Unset default port on Update

aws-rds-optiongroup/inputs/inputs_1_create.json, aws-rds-optiongroup/inputs/inputs_1_update.json, aws-rds-optiongroup/src/main/java/software/amazon/rds/optiongroup/BaseHandlerStd.java, aws-rds-optiongroup/src/test/java/software/amazon/rds/optiongroup/CreateHandlerTest.java
This PR fixes Contract tests for OptionGroup. In addition, this PR also prevents OptionGroup resource created outside of CFN being overriden by custom-named option group.
=> [OptionGroup] Fix contract tests for option group

aws-rds-dbclusterendpoint/aws-rds-dbclusterendpoint.json, aws-rds-dbclusterendpoint/docs/README.md, aws-rds-dbclusterendpoint/src/main/java/software/amazon/rds/dbclusterendpoint/CallbackContext.java, aws-rds-dbclusterendpoint/src/main/java/software/amazon/rds/dbclusterendpoint/CreateHandler.java, aws-rds-dbclusterendpoint/src/main/java/software/amazon/rds/dbclusterendpoint/ReadHandler.java, aws-rds-dbclusterendpoint/src/main/java/software/amazon/rds/dbclusterendpoint/UpdateHandler.java, aws-rds-dbclusterendpoint/src/test/java/software/amazon/rds/dbclusterendpoint/ReadHandlerTest.java
This PR fixes Read handler on DBClusterEndpoint and relaxes the schema definition in order to make errors more human-friendly.
=> [DBClusterEndpoint] Fix read handler, relax schema constraints

aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/BaseHandlerStd.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/CreateHandler.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/Translator.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/util/ResourceModelHelper.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/TranslatorTest.java
This commit moves modify-after-create Translator to a separate method. The motivation for this change is to get rid of an overly-complicated logic in the current implementation of `Translator.modifyDbInstanceRequest`. There is a significant difference between a regular update and an update after create that is only supposed to concern a limited set of attributes. An example of this logic is handling iops or allocatedStorage parameters.
=> [DBInstance] Move modify-after-create to a standalone method

aws-rds-cfn-common/pom.xml, aws-rds-customdbengineversion/pom.xml, aws-rds-dbcluster/pom.xml, aws-rds-dbclusterendpoint/pom.xml, aws-rds-dbclusterparametergroup/pom.xml, aws-rds-dbinstance/pom.xml, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/client/RdsClientProviderTest.java, aws-rds-dbparametergroup/pom.xml, aws-rds-dbsubnetgroup/pom.xml, aws-rds-eventsubscription/pom.xml, aws-rds-globalcluster/pom.xml, aws-rds-optiongroup/pom.xml
This commit bumps all package aws sdk versions to `2.18.24`. The motivation for the change is a potential regression introduced by a recent SDK release.
A test regression was noticed in https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-rds/pull/353/files#diff-608a303a115402d9a7b63d5e9a01808ea8b66ea1508f49e6d5d4115354c4fa83R94-R95. There was a failure in `RdsClientProviderTest` probing the presence of the provided version in the RDS API request body.
The SDK was patched and re-released, hence we are reverting the disabled test.
=> [All] Bump AWS SDK version to 2.18.24

aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/BaseHandlerStd.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/Translator.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/TranslatorTest.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/UpdateHandlerTest.java
This commit alters the modify-db-instance ruleset. `InvalidParameterCombinationException` is interpreted as a `HandlerErrorCode.ResourceConflict`, which causes retries on modify-db-instance requests that would guarantee to fail no matter the retries. This commit moves the exception to the `HandlerErrorCode.InvalidInput`, so the handler fails fast.
=> [DBInstance] No retry on `InvalidParameterCombinationException`

aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/Translator.java, aws-rds-dbcluster/src/test/java/software/amazon/rds/dbcluster/CreateHandlerTest.java
This commit adds a missing `enableCloudwatchLogsExports` attribute to the `RestoreDbClusterToPointInTimeRequest`.
Refs https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/1426
=> [DBCluster] Set `enableCloudwatchLogsExports` on `RestoreDbClusterToPointInTimeRequest`

aws-rds-dbcluster/aws-rds-dbcluster.json, aws-rds-dbcluster/docs/README.md
This PR updates the documentation of DBSystemId to be keep parity with the current public documentation https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/rds/model/DBCluster.html#dbSystemId()
=> [DBCluster] Update documentation for DBSystemId property

aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/Translator.java
This PR fixes the previous [PR](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-rds/pull/349) which was supposed to fix the update behaviour of the PubliclyAccessible property from Replacement to No interruption but it returns the same value of the previous template. 
=> [DBInstance] Update PubliclyAccessible property

aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/StorageType.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/Translator.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/util/ResourceModelHelper.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/TranslatorTest.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/util/ResourceModelHelperTest.java
This PR addresses the issue with DBInstance RestoreDBInstanceFromDBSnapshot workflow when gp3 storage is used. It is not possible to specify allocated storage size during restore, which results in invalid requests. This change omits setting storage type for GP3 and defers update to correct values to ModifyAfterCreate.
=> [DBInstance] Correct RestoreDBInstanceFromDBSnapshot workflow when gp3 storage is used

aws-rds-dbinstance/aws-rds-dbinstance.json, aws-rds-dbinstance/docs/README.md, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/Translator.java
This PR exposes read-only property DBSystemID for DBInstance. 
=> [DBInstance] Add DBSystemID read-only property

aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/Translator.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/TranslatorTest.java
This commit changes the handler behavior on a rollback update. The current strategy is to ensure `AllocatedStorage` and `Iops` changeability. Effectively, this means that the handler would ensure that neither of these attributes is being reduced upon a rollback. An attempt to reduce the corresponding attribute is known to be rejected by the RDS API, hence the handler would keep the old (pre-rollback) value. This commit alters this strategy to providing no pre-rollback values at all if either of these attributes is identifier as non-updatable. The translator would provide a null-value instead.
The motivation behind this change is to expand the applicability of the "keep whatever is working" on a case when the initial update failed. The existing approach would only work if the initial …
=> [DBInstance] Unset `AllocatedStorage` and `Iops` on rollback

aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/Translator.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/TranslatorTest.java
This commit changes the way CREATE and UPDATE handlers deal with performance insights argument pair: `EnablePerformanceInsights`(EPI) and `PerformanceInsightsKMSKeyId`(PKI). RDS API is sensitive to attempts to modify PKI if performance insights is disabled. The key id must be provided all the time when EPI attribute changes the value.
The following `CREATE` logic is implemented:
- If EPI is enabled, include both EPI and PKI in the request.
- If EPI is disabled, include none of EPI and PKI. If PKI was provided, RDS API would reject the request. This case creates a drift, but it seems to be the only reasonable way to allow EPI enablement with a minimal change on the customer side.
The following `UPDATE` logic is implemented:
- If none of EPI and PKI were changed, include none of EPI and …
=> [DBInstance] Handle performance insights enablement toggle

aws-rds-cfn-common/pom.xml, aws-rds-cfn-test-common/src/main/java/software/amazon/rds/test/common/core/ServiceProvider.java, aws-rds-customdbengineversion/pom.xml, aws-rds-dbcluster/aws-rds-dbcluster.json, aws-rds-dbcluster/docs/README.md, aws-rds-dbcluster/docs/masterusersecret.md, aws-rds-dbcluster/pom.xml, aws-rds-dbcluster/resource-role.yaml, aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/BaseHandlerStd.java, aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/Translator.java, aws-rds-dbcluster/src/test/java/software/amazon/rds/dbcluster/TranslatorTest.java, aws-rds-dbclusterendpoint/pom.xml, aws-rds-dbclusterparametergroup/pom.xml, aws-rds-dbinstance/aws-rds-dbinstance.json, aws-rds-dbinstance/docs/README.md, aws-rds-dbinstance/docs/masterusersecret.md, aws-rds-dbinstance/pom.xml, aws-rds-dbinstance/resource-role.yaml, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/BaseHandlerStd.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/Translator.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/BaseHandlerStdTest.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/ListHandlerTest.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/TranslatorTest.java, aws-rds-dbparametergroup/pom.xml, aws-rds-dbsubnetgroup/pom.xml, aws-rds-eventsubscription/pom.xml, aws-rds-globalcluster/pom.xml, aws-rds-optiongroup/pom.xml
This PR adds support for [password management](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/rds-secrets-manager.html) with  AWS SecretsManager for DBInstance and DBCluster resources
=> [DBInstance][DBCluster] Add support for SecretsManager integration

aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/BaseHandlerStd.java, aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/CreateHandler.java, aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/UpdateHandler.java, aws-rds-dbcluster/src/test/java/software/amazon/rds/dbcluster/UpdateHandlerTest.java
This commit alters the error rule set for adding associated roles to DBCluster. The current implementation soft-fails an already-exists exception for historical reasons.
The error can occur in 2 major cases:
- Update failed to remove a role and a rollback would fail due to a resource conflict.
- The same role was added under distinct feature names and this specific engine requires all roles to be unique.
This CR preserves soft-failing for a failed rollback (recovery mode) but exposes `DbClusterRoleAlreadyExistsException` on a regular update.
Refs https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-rds/issues/373. …
=> [DBCluster] Report `DbClusterRoleAlreadyExistsException` exception

aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/util/ImmutabilityHelper.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/util/ImmutabilityHelperTest.java
This commit addresses a null-pointer exception in `ImmutabilityHelper.isAvailabilityZoneChangeMutable` that might occur if `DBInstance.MultiAZ` is not provided and the handler attempts to alter the instance's `AvailabilityZone` attribute. The commit adds a `BooleanUtils` safety guard to ensure no null-deref would occur.
=> [DBInstance] Fix null-pointer exception in `ImmutabilityHelper`

aws-rds-cfn-common/pom.xml, aws-rds-customdbengineversion/pom.xml, aws-rds-dbclusterendpoint/pom.xml, aws-rds-dbclusterparametergroup/pom.xml, aws-rds-dbinstance/pom.xml, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/Translator.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/util/ResourceModelHelper.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/CreateHandlerTest.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/TranslatorTest.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/util/ResourceModelHelperTest.java, aws-rds-dbparametergroup/pom.xml, aws-rds-dbsubnetgroup/pom.xml, aws-rds-eventsubscription/pom.xml, aws-rds-globalcluster/pom.xml, aws-rds-optiongroup/pom.xml
This PR modifies DBInstance in a way that would remove `storage-optimization` step when restoring DBInstance from Snapshot or restoring instance to Point in time.
=> [DBInstance] Allocated storage size workflow improvements

aws-rds-cfn-test-common/pom.xml, aws-rds-cfn-test-common/src/main/java/software/amazon/rds/test/common/schema/ResourceDriftTestHelper.java, aws-rds-cfn-test-common/src/test/java/software/amazon/rds/test/common/schema/ResourceDriftTestHelperTest.java, aws-rds-dbcluster/aws-rds-dbcluster.json, aws-rds-dbcluster/src/test/java/software/amazon/rds/dbcluster/SchemaTest.java, aws-rds-dbclusterendpoint/src/main/java/software/amazon/rds/dbclusterendpoint/Configuration.java, aws-rds-dbclusterendpoint/src/test/java/software/amazon/rds/dbclusterendpoint/SchemaTest.java, aws-rds-dbclusterparametergroup/src/main/java/software/amazon/rds/dbclusterparametergroup/Configuration.java, aws-rds-dbclusterparametergroup/src/test/java/software/amazon/rds/dbclusterparametergroup/SchemaTest.java, aws-rds-dbinstance/aws-rds-dbinstance.json, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/SchemaTest.java, aws-rds-dbparametergroup/src/test/java/software/amazon/rds/dbparametergroup/SchemaTest.java, aws-rds-dbsubnetgroup/src/main/java/software/amazon/rds/dbsubnetgroup/Configuration.java, aws-rds-dbsubnetgroup/src/test/java/software/amazon/rds/dbsubnetgroup/SchemaTest.java, aws-rds-eventsubscription/src/main/java/software/amazon/rds/eventsubscription/Configuration.java, aws-rds-eventsubscription/src/test/java/software/amazon/rds/eventsubscription/SchemaTest.java, aws-rds-optiongroup/src/test/java/software/amazon/rds/optiongroup/SchemaTest.java
This commit implements a new test helper called `ResourceDriftTestHelper`. This is an assertion helper that checks if there is a drift between an input and an output, based on the resource schema definition provided.
In particular, the drift detector would engage `propertyTransform` instructions from the schema and compare the transform formula result with the output. If neither the original input value nor any of the transformation outputs match the output, the resource is considered to have drifted.
=> [Common] Implement Drift Detector Test Helper

aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/BaseHandlerStd.java
This commit updates the list of predicates which is used to detect failure events upon a DBInstance stabilization. The list gets a new matcher. The matcher would perform a case-insensitive match now.
This change is a follow-up on https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-rds/pull/345
=> [DBInstance] Update event-matching predicates

aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/Translator.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/TranslatorTest.java
This PR addresses an issue when customer updates only Iops or AllocatedStorageSize value for the instance that uses IO1 storage type. Previously, such requests would fail because both parameters must be present. Now such updates should succeed. 
In other cases AllocatedStorageSize is omitted in order to prevent unwanted StorageOptimization step.
=> [DBInstance] Set AllocatedStorage/Iops unconditionally on Update if IO1 Storage type is used

aws-rds-cfn-test-common/src/main/java/software/amazon/rds/test/common/schema/ResourceDriftTestHelper.java, aws-rds-dbcluster/aws-rds-dbcluster.json, aws-rds-dbcluster/src/test/java/software/amazon/rds/dbcluster/SchemaTest.java
This commit addresses known false drift detection on the following attributes:
- `EnableHttpEndpoint`
- `PreferredMaintenanceWindow`
=> [DBCluster] Resolve false drift detection

aws-rds-cfn-common/src/main/java/software/amazon/rds/common/handler/Commons.java, aws-rds-cfn-common/src/test/java/software/amazon/rds/common/handler/CommonsTest.java
This commit adds another SDK-related exception class to the default error rule set. The semantics of `SdkServiceException` is pretty similar to `SdkClientException`, with the difference that the issue occurred on the server side (e.g. backend unavailable).
The exception is being handled as an internal service error and hence would be retried.
=> [Common] Handle `SdkServiceException`

aws-rds-cfn-test-common/src/main/java/software/amazon/rds/test/common/schema/ResourceDriftTestHelper.java, aws-rds-dbcluster/aws-rds-dbcluster.json, aws-rds-dbcluster/src/test/java/software/amazon/rds/dbcluster/SchemaTest.java, aws-rds-dbinstance/aws-rds-dbinstance.json, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/SchemaTest.java
This commit introduces an additional propertyTransform directive to DBInstance and DBCluster schemas. The transformation would be used by the drift detector to compare engine versions. The original input value is used as a prefix:
- Assume only major version "5" is provided.
- Resulting version "5.6.40" is not a drift.
- Resulting version "5.6.40.patch1" is not a drift.
- Resulting version "8.0.0" is a drift.
- Assume major and minor versions are provided: "5.6".
- Resulting version "5.6.40" is not a drift.
- Resulting version "5.6.40.patch1" is not a drift.
- Resulting version "5.12.1" is a drift.
- Resulting version "8.0.0" is a drift. …
=> [DBInstance][DBCluster] Fix false drift on EngineVersion

aws-rds-dbclusterparametergroup/src/main/java/software/amazon/rds/dbclusterparametergroup/BaseHandlerStd.java, aws-rds-dbclusterparametergroup/src/main/java/software/amazon/rds/dbclusterparametergroup/Translator.java, aws-rds-dbclusterparametergroup/src/test/java/software/amazon/rds/dbclusterparametergroup/TranslatorTest.java
This commit limits the parameter name filter size to 100 elements per request. RDS API would reject a request containing more than 100 parameter names in the filter. The commit removes the recursive progressChain tailing and proposes a simplistic sequential current parameter accumulator buildup.
=> [DBClusterParameterGroup] Limit max filter size to 100

aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/Translator.java, aws-rds-dbcluster/src/test/java/software/amazon/rds/dbcluster/TranslatorTest.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/Translator.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/util/ResourceModelHelper.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/ListHandlerTest.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/TranslatorTest.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/util/ResourceModelHelperTest.java
This PR is a followup on SecretsManager integration implementation that addresses a few things:
* Correctly apply SecretsManager related modifications for RestoreFromSnapshot scenario
* Address false positive drift detection when ManageMasterUserPassword was involved for DBCluster/DBInstace
=> [DBInstance][DBCluster] Address scenario when Restored from Snapshot DBInstance/DCluster opts in into SecretsManager integration

aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/Translator.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/TranslatorTest.java
This commit adds a missing attribute `copyTagsToSnapshot` to the `RestoreDbInstanceFromSnapshot` translator routine. The motivation for this change is to achieve a cross-create-method consistency as the attribute is supported in all create methods used in the DBInstance handler.
=> [DBInstance] Set `copyTagsToSnapshot` on `RestoreDbInstanceFromSnapshot`

aws-rds-dbsubnetgroup/src/main/java/software/amazon/rds/dbsubnetgroup/Translator.java, aws-rds-dbsubnetgroup/src/test/java/software/amazon/rds/dbsubnetgroup/TranslatorTest.java
This PR addresses the issue when subnetIDs contain extraneous white-space characters. Before this change, white-space padded SubnetIds would be silently treated as non-existing subnets, which potentially could result in unintentional removal of such subnets from DBSubnetGroup. This change removes whitespace-padding , eliminating the issue.
=> [DBSubnetGroup] Trim whitespaces for subnetIDs when building Create and Modify DBSubnetGroup requests

aws-rds-dbinstance/aws-rds-dbinstance.json
This commit marks `DeleteAutomatedBackups` as a write-only property. The morivation for this change is to align this attribute behavior with its purpose: the flag is semi-virtual and is only used upon a delete. Up until this point it is an ephemeural attribute that is not stored anywhere, hence bugging CFN users with false drift detector alarms.
Fixes https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/1510.
Refs https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-rds/issues/400.
=> [DBInstance] Mark `DeleteAutomatedBackups` as WriteOnly

aws-rds-dbinstance/aws-rds-dbinstance.json
This commit marks `AllowMajorVersionUpgrade` as a write-only property. The motivation is similar to
https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-rds/pull/401 in terms of the nature of the attribute: the RDS API won't accept it upon a create and won't serve it back with a describe-db-instances. The flag is only used upon a modify request to indicate that a major engine version could be changed.
Refs https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-rds/issues/400.
Fixes https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/1511.
Signed-off-by: Oleg Sidorov …
=> [DBInstance] Mark `AllowMajorVersionUpgrade` as WriteOnly

aws-rds-cfn-common/src/main/java/software/amazon/rds/common/printer/FilteredJsonPrinter.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/Translator.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/TranslatorTest.java
This commit addresses an issue with an empty `MasterUserSecret` input upon a DBInstance modification. The attribute itself is optional even when `ManageMasterUserPassword` is set to true: the service would use a pre-provisioned KMS key instead.
=> [DBInstance] Fix empty `MasterUserSecret` on Update

aws-rds-dbcluster/aws-rds-dbcluster.json, aws-rds-dbcluster/src/test/java/software/amazon/rds/dbcluster/SchemaTest.java, aws-rds-dbinstance/aws-rds-dbinstance.json, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/SchemaTest.java
This PR addresses the drift on Engine property. RDS service accepts `Engine` inputs in a case insensitive mode, meanwhile CFN detects false drift since return value for engine is always in lowercase.
=> [DBInstance][DBCluster] Address drift on Engine property

aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/BaseHandlerStd.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/Translator.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/BaseHandlerStdTest.java
This commit removes `PromotionTier` from the stabilization attributes. The reason for this change is that `PromotionTier` is a customer-controlled attribute and RDS API won't alter it on its own.
=> [DBInstance] Remove stabilization on `PromotionTier`

aws-rds-dbinstance/aws-rds-dbinstance.json, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/SchemaTest.java
This commit adds a property transform instruction to account for a case-insensitive DBName conversion.
Fixes https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/1530.
=> [DBInstance] Fix DBName drift

aws-rds-dbinstance/aws-rds-dbinstance.json, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/SchemaTest.java
Oracle engine uppercases the database name. This causes a false drift alarm. This commit adds uppercased DBName spelling to the list of valid options RDS API could return.
Fixes https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/1530.
=> [DBInstance] Fix false drift detection on Oracle DBName

aws-rds-cfn-common/src/main/java/software/amazon/rds/common/logging/LoggingProxyClient.java, aws-rds-cfn-common/src/main/java/software/amazon/rds/common/printer/FilteredJsonPrinter.java, aws-rds-cfn-common/src/test/java/software/amazon/rds/common/logging/LoggingProxyClientTest.java, aws-rds-cfn-test-common/src/main/java/software/amazon/rds/test/common/verification/AccessPermissionAlias.java, aws-rds-cfn-test-common/src/main/java/software/amazon/rds/test/common/verification/AccessPermissionVerificationMode.java, aws-rds-cfn-test-common/src/test/java/software/amazon/rds/test/common/verification/AccessPermissionTest.java, aws-rds-cfn-test-common/src/test/java/software/amazon/rds/test/common/verification/AccessPermissionVerificationModeTest.java, aws-rds-dbparametergroup/aws-rds-dbparametergroup.json, aws-rds-dbparametergroup/src/main/java/software/amazon/rds/dbparametergroup/BaseHandlerStd.java, aws-rds-dbparametergroup/src/main/java/software/amazon/rds/dbparametergroup/ReadHandler.java, aws-rds-dbparametergroup/src/main/java/software/amazon/rds/dbparametergroup/Translator.java, aws-rds-dbparametergroup/src/test/java/software/amazon/rds/dbparametergroup/AbstractTestBase.java, aws-rds-dbparametergroup/src/test/java/software/amazon/rds/dbparametergroup/BaseHandlerStdTest.java, aws-rds-dbparametergroup/src/test/java/software/amazon/rds/dbparametergroup/CreateHandlerTest.java, aws-rds-dbparametergroup/src/test/java/software/amazon/rds/dbparametergroup/ReadHandlerTest.java, aws-rds-dbparametergroup/src/test/java/software/amazon/rds/dbparametergroup/TranslatorTest.java, aws-rds-dbparametergroup/src/test/java/software/amazon/rds/dbparametergroup/UpdateHandlerTest.java
This commit adds `DBParameterGroup.parameters` in the `ReadHandler` response. The motivation for this change is to enable drift detector on independent group parameters. At the moment this collection is defined as `WriteOnly`, instructing the drift detector to ignore it completely.
=> [DBParameterGroup] Include parameters in the `ReadHandler` response

aws-rds-dbinstance/aws-rds-dbinstance.json, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/SchemaTest.java
This PR prevents false drift on PreferredMaintenanceWindow property. It is returned in lowercase by API, this change accounts for that.
=> [DBInstance] Compare PreferredMaintenanceWindow case insensitevely to prevent false drift

aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/Translator.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/util/ResourceModelHelper.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/TranslatorTest.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/util/ResourceModelHelperTest.java
This commit enables modify-after-create handler step on instances that are being restored from a snapshot and have `EnablePerformanceInsights` set to true. The flag was not set previously becuase `RestoreDBInstanceFromDBSnapshot` would not expose the corresponding attribute and CFN would detect a false resource drift.
=> [DBInstance] Set `EnablePerformanceInsights` on Restore

aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/Translator.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/util/ResourceModelHelper.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/TranslatorTest.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/util/ResourceModelHelperTest.java
This commit fixes a false drift detection on DBInstance resources when they are being restore from a snapshot with enabled enhanced monitoring. The commit enforces an update-after-create operation on restorable instances if the monitoring is on.
Documentation: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_Monitoring.OS.Enabling.html#USER_Monitoring.OS.Enabling.Prerequisites
Refs https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/1569.
=> [DBInstance] Fix drift on enhanced monitoring when restoring from a snapshot

aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/util/ResourceModelHelper.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/AbstractHandlerTest.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/CreateHandlerTest.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/util/ResourceModelHelperTest.java
This PR modifies logic for ModifyAfterCreate when storage parameters were updated. Previously, modify request would run for any engine if storage parameters were modified. Now modify only runs for SQL server.
In addition, previously if storage type was set on DBInstance, modify after create workflow would not run. Now it correctly triggers modify after create.
=> [DBInstance] Modify after create - storage parameters fixes

aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/Translator.java, aws-rds-dbcluster/src/test/java/software/amazon/rds/dbcluster/CreateHandlerTest.java, aws-rds-dbcluster/src/test/java/software/amazon/rds/dbcluster/TranslatorTest.java
This PR fixes an issue with restore scenarios for DBCluster where setting Serverless v2 config twice would occasionally return InternalErrors when setting ServerlessV2 config on Modify Call that followed restore.
=> [DBCluster] Only set ServerlessV2 scaling configuration once during restore scenarios

aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/Translator.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/TranslatorTest.java
This commit changes ModifyAfterCreate method of the Translator class. The method is instructed to pass the performance insights(PI) kms key ID if PI is enabled. RDS API expects the key ID upon every modify request if the instance was created with PI enabled and a key ID was provided.
=> [DBInstance] Set performance insights key on modify-after-create

aws-rds-dbcluster/aws-rds-dbcluster.json, aws-rds-dbcluster/src/test/java/software/amazon/rds/dbcluster/SchemaTest.java, aws-rds-dbinstance/aws-rds-dbinstance.json, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/SchemaTest.java
This commit enables case-insensitive drift detection on `NetworkType`. The RDS API downcases the input which might cause a false drift.
=> [DBInstance][DBCluster] Case-insensitive NetworkType drift detection

aws-rds-dbcluster/aws-rds-dbcluster.json, aws-rds-dbcluster/src/test/java/software/amazon/rds/dbcluster/SchemaTest.java, aws-rds-dbinstance/aws-rds-dbinstance.json, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/SchemaTest.java
This commit adds an additional `PropertyTransform` directive for `StorageType` in both `DBInstance` and `DBCluster` resources. The motivation for the change is to eliminate a false drift detection on this attribute that occurs on the lowercase-coalescing done by RDS API.
=> [DBInstance][DBCluster] Fix drift detection on `StorageType`

aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/CreateHandler.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/CreateHandlerTest.java
This commit alters the behavior of the the create handler upon a restore from a snapshot.
The restore procedure differs depending on the engine provided in the request. SQL server engines would reject storage-related set of attributes and would expect these values to be sent with a follow-up modify-after-create request. For non-SQL engines storage-related attributes could be provided as a part of the initial `RestoreDBInstanceFromDBSnapshot` request.
The issue occurs when CFN restore request contains no specific engine name: the current implementation assumes this is a SQL engine family and performs the restore-and-update scenario.
This change instructs the handler to get the engine name from the snapshot and to make a more conscious decision on the SQL/non-SQL branching. In this scenario …
=> [DBInstance] Set engine from snapshot on restore-from-snapshot

aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/Translator.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/util/ResourceModelHelper.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/CreateHandlerTest.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/TranslatorTest.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/util/ResourceModelHelperTest.java
Previously DBInstance handlers assumed that only SQL Server needs to update storage parameters on ModifyAfterCreate scenarios. This PR changes this logic to update the storage parameters if storage parameters were modified.
The main motivation behind this change is that the customers are able to omit Engine for their DBInstance. That in turn requires us to fetch Engine of the future SQL Instance from DBSnapshot, DBClusterSnapshot, read replica's primary instance, etc. Not all scenarios were covered, leading to instance having wrong storage parameters.
=> [DBInstance] Set storage parameters on ModifyAfterCreate workflows if they are specified in the model

aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/Translator.java, aws-rds-dbcluster/src/test/java/software/amazon/rds/dbcluster/TranslatorTest.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/Translator.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/TranslatorTest.java
Fix an error when Modify call would fail if the customer has set `ManageMasterUserPassword` to false explicitly. If the customer also does  not change their password in the same operation, RDS would reject the change stating that `MasterUserPassword` is required when `ManageMasterUserPassword` is false.
With this change DBInstance and DBCluster update handlers omit sending `ManageMasterUserPassword` parameter when it is not changed in the template.
=> [DBInstance][DBCluster] Fix update scenarios when ManageMasterUserPassword is unchanged

aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/Translator.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/util/ResourceModelHelper.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/CreateHandlerTest.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/TranslatorTest.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/util/ResourceModelHelperTest.java
This PR is a follow-up on  #438 which addresses more corner cases by not specifying Storage parameters on initial calls. This way engines that do not support those parameters on initial call can be properly updated
=> [DBInstance] Address corner cases for storage parameters used with ModifyAfterCreate workflows

aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/BaseHandlerStd.java, aws-rds-dbcluster/src/test/java/software/amazon/rds/dbcluster/CreateHandlerTest.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/BaseHandlerStd.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/BaseHandlerStdTest.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/CreateHandlerTest.java
This commit addresses a role mutate stabilization issue that occurs if the role association feature name is an empty string. RDS API treats this as a no-value and returns an null feature name back. Both `DBInstance` and `DBCluster` handlers stabilize on both `RoleARN` and `FeatureName` attributes upon an addition, hence this discrepancy between an empty string and a null value cause an infinite stabilization.
=> [DBCluster][DBInstance] Fix empty feature name in `AssiciatedRoles`

aws-rds-dbinstance/aws-rds-dbinstance.json
The motivation for this change is to get aligned with the SDK which does not expose the attribute for the describe API interface. I.e. the attribute is write-only from the API perspective, hence keeping it as read-write would cause a false drift.
=> [DBInstance] Mark `UseDefaultProcessorFeatures` as write-only

aws-rds-cfn-common/src/main/java/software/amazon/rds/common/handler/Tagging.java, aws-rds-customdbengineversion/src/main/java/software/amazon/rds/customdbengineversion/BaseHandlerStd.java, aws-rds-customdbengineversion/src/test/java/software/amazon/rds/customdbengineversion/UpdateHandlerTest.java, aws-rds-dbclusterendpoint/src/main/java/software/amazon/rds/dbclusterendpoint/ReadHandler.java, aws-rds-dbclusterparametergroup/src/main/java/software/amazon/rds/dbclusterparametergroup/BaseHandlerStd.java, aws-rds-dbclusterparametergroup/src/main/java/software/amazon/rds/dbclusterparametergroup/ReadHandler.java, aws-rds-dbparametergroup/src/main/java/software/amazon/rds/dbparametergroup/BaseHandlerStd.java, aws-rds-dbparametergroup/src/main/java/software/amazon/rds/dbparametergroup/ReadHandler.java, aws-rds-dbsubnetgroup/src/main/java/software/amazon/rds/dbsubnetgroup/BaseHandlerStd.java, aws-rds-dbsubnetgroup/src/main/java/software/amazon/rds/dbsubnetgroup/ReadHandler.java, aws-rds-eventsubscription/src/main/java/software/amazon/rds/eventsubscription/BaseHandlerStd.java, aws-rds-eventsubscription/src/main/java/software/amazon/rds/eventsubscription/ReadHandler.java, aws-rds-optiongroup/src/main/java/software/amazon/rds/optiongroup/BaseHandlerStd.java, aws-rds-optiongroup/src/main/java/software/amazon/rds/optiongroup/CallbackContext.java, aws-rds-optiongroup/src/main/java/software/amazon/rds/optiongroup/ReadHandler.java, aws-rds-optiongroup/src/test/java/software/amazon/rds/optiongroup/UpdateHandlerTest.java
Due to the absence of the tags attribute in the response of many Describe calls, only resources such as DBInstance, DBCluster, and CustomDBEngineVersion include tags in their describe call. For other resources, it is necessary to make a separate ListTagsForResource call to retrieve tags. In order to avoid inconveniencing customers who do not have List permission, this call is handled with soft failure, ensuring that they are not penalized for lacking the necessary permission.
=> [Common][All] Fix List Tags Soft Failure Parity in Read Handlers 

aws-rds-dbcluster/aws-rds-dbcluster.json, aws-rds-dbcluster/resource-role.yaml, aws-rds-dbclusterparametergroup/aws-rds-dbclusterparametergroup.json, aws-rds-dbclusterparametergroup/resource-role.yaml, aws-rds-dbparametergroup/aws-rds-dbparametergroup.json, aws-rds-dbparametergroup/resource-role.yaml, aws-rds-dbsubnetgroup/aws-rds-dbsubnetgroup.json, aws-rds-dbsubnetgroup/resource-role.yaml, aws-rds-eventsubscription/aws-rds-eventsubscription.json, aws-rds-eventsubscription/resource-role.yaml, aws-rds-optiongroup/aws-rds-optiongroup.json, aws-rds-optiongroup/resource-role.yaml
Cloudformation handlers need to specify which permissions are required to perform the operations requested by customers. This CR adds CreateServiceLinkedRole on create for other resources similar to what is being done for DbInstance
=> Add iam CreateServiceLinkedRole permissions

aws-rds-cfn-common/src/main/java/software/amazon/rds/common/handler/Tagging.java, aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/BaseHandlerStd.java, aws-rds-dbclusterendpoint/docs/README.md, aws-rds-dbclusterendpoint/docs/tag.md, aws-rds-dbclusterendpoint/src/main/java/software/amazon/rds/dbclusterendpoint/BaseHandlerStd.java, aws-rds-dbclusterparametergroup/src/main/java/software/amazon/rds/dbclusterparametergroup/BaseHandlerStd.java, aws-rds-dbclusterparametergroup/src/test/java/software/amazon/rds/dbclusterparametergroup/AbstractHandlerTest.java, aws-rds-dbclusterparametergroup/src/test/java/software/amazon/rds/dbclusterparametergroup/UpdateHandlerTest.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/BaseHandlerStd.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/UpdateHandlerTest.java, aws-rds-dbparametergroup/src/main/java/software/amazon/rds/dbparametergroup/BaseHandlerStd.java, aws-rds-dbsubnetgroup/src/main/java/software/amazon/rds/dbsubnetgroup/BaseHandlerStd.java, aws-rds-eventsubscription/src/main/java/software/amazon/rds/eventsubscription/BaseHandlerStd.java, aws-rds-optiongroup/src/main/java/software/amazon/rds/optiongroup/BaseHandlerStd.java
This PR makes sure that Resource level tags always take precedence over stack level tags. If there is a collision between stack and resource level tags, previously erroneous AddTagsToResource or RemoveTagsFromResource requests could be sent. This PR addresses this issue. 
=> [All] Fix tagging when stack and resource level tags have jey collisions

aws-rds-customdbengineversion/src/main/java/software/amazon/rds/customdbengineversion/ListHandler.java, aws-rds-customdbengineversion/src/main/java/software/amazon/rds/customdbengineversion/Translator.java, aws-rds-customdbengineversion/src/test/java/software/amazon/rds/customdbengineversion/ListHandlerTest.java
In this code modification, I have adjusted the behavior to only return the custom engine versions that have been created, rather than returning all engine versions present in RDS.
=> [CustomDBEngineVersion] Update ListHandler logic to return only created custom

.gitignore, aws-rds-cfn-common/pom.xml, aws-rds-customdbengineversion/pom.xml, aws-rds-dbcluster/pom.xml, aws-rds-dbclusterendpoint/pom.xml, aws-rds-dbclusterparametergroup/pom.xml, aws-rds-dbinstance/docs/README.md, aws-rds-dbinstance/pom.xml, aws-rds-dbparametergroup/pom.xml, aws-rds-dbsubnetgroup/pom.xml, aws-rds-eventsubscription/pom.xml, aws-rds-globalcluster/pom.xml, aws-rds-optiongroup/pom.xml
This enables the resource to access the upcoming Integration resource.
*Issue #, if available:* https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-rds/issues/485
*Description of changes:* 
- Updating the AWS SDK version to 2.21.17 which exposes the Zero ETL API
- All other changes are due to the SDK version changes (documentation generator changes)
=> [All] Update AWS SDK version to 2.21.17

aws-rds-dbinstance/pom.xml, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/Translator.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/TranslatorTest.java
- Adds missing flag AllowMajorUpgrade to modify call  made during create for DBInstance.
- Adds unit test to ensure parameter is present
=> [DBInstance] Add AllowMajorUpgrade on ModifyAfterCreate

aws-rds-dbcluster/aws-rds-dbcluster.json, aws-rds-dbcluster/docs/README.md, aws-rds-dbcluster/pom.xml, aws-rds-dbcluster/resource-role.yaml, aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/BaseHandlerStd.java, aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/CreateHandler.java, aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/Translator.java, aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/UpdateHandler.java, aws-rds-dbcluster/src/test/java/software/amazon/rds/dbcluster/BaseHandlerStdTest.java, aws-rds-dbcluster/src/test/java/software/amazon/rds/dbcluster/SchemaTest.java
Onboarding DBCluster to Data API version 2 feature, In the create scenario, We can enable it directly by including it in the createDBCluster API call. However, it is not supported in the RestoreDbClusterToPointInTime, RestoreDbClusterFromSnapshot, and ModifyDbCluster operations. Therefore, an additional call is necessary to enable or disable the HTTP endpoint.
Previously, the RDS webservice would disregard the false flag in the HttpEndpoint for engines that do not support the HTTP endpoint. As a result, we now ignore the unsupported fault when disabling the HTTP endpoint for the sake of backward compatibility.
Ref: https://aws.amazon.com/blogs/database/introducing-the-data-api-for-amazon-aurora-serverless-v2-and-amazon-aurora-provisioned-clusters/
By submitting …
=> [DBCluster] Support EnableHttpEndpoint for Aurora Postgres engine to support Data Api V2.

aws-rds-integration/src/main/java/software/amazon/rds/integration/BaseHandlerStd.java
https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-rds/issues/499
*Issue #, if available:* #499
*Description of changes:* https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_CreateIntegration.html
The maximum length for the integration is 63, not 64.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice. - YES
=> [Integration] Correct the maximum name length for Integration

aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/CreateHandler.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/Translator.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/util/ImmutabilityHelper.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/util/ResourceModelHelper.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/CreateHandlerTest.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/util/ResourceModelHelperTest.java
Revert isEngineMutable check to use previous model for same engine check
=> [DBInstance] Revert isEngineMutable check to use previous model for same engine check

aws-rds-cfn-common/src/main/java/software/amazon/rds/common/printer/FilteredJsonPrinter.java
This code removes ReflectionToStringBuilder which is not supported on Java17 and uses PrintWriter to serialize the throwable stack trace instead.
=> [Common] Remove reflection when serializing stack trace

aws-rds-customdbengineversion/src/main/java/software/amazon/rds/customdbengineversion/CreateHandler.java, aws-rds-dbcluster/aws-rds-dbcluster.json, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/CreateHandler.java, aws-rds-integration/docs/README.md
Removing the range validation from DBCluster ServerlessV2ScalingConfiguration. RDS Webservice will handle the validation and provide a more helpful error message if there is a problem.
=> [DBCluster] Removing the range validation from DBCluster  ServerlessV2ScalingConfiguration

aws-rds-cfn-common/src/main/java/software/amazon/rds/common/error/ErrorStatus.java, aws-rds-cfn-common/src/main/java/software/amazon/rds/common/error/RetryErrorStatus.java, aws-rds-cfn-common/src/main/java/software/amazon/rds/common/handler/Commons.java, aws-rds-cfn-common/src/test/java/software/amazon/rds/common/error/ErrorStatusTest.java, aws-rds-integration/src/main/java/software/amazon/rds/integration/BaseHandlerStd.java, aws-rds-integration/src/main/java/software/amazon/rds/integration/CreateHandler.java, aws-rds-integration/src/main/java/software/amazon/rds/integration/DeleteHandler.java, aws-rds-integration/src/test/java/software/amazon/rds/integration/CreateHandlerTest.java, pom.xml
Retry on IntegrationConflictOperation
*Issue #, if available:* N/A
*Description of changes:* The resource is too  sensitive to transient errors such as IntegrationConflictOperationException which is retriable. This PR corrects those flaky behaviours. 
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice. - YES
=> Robustness improvements for AWS::RDS::Integration

.gitignore, aws-rds-cfn-common/pom.xml, aws-rds-cfn-common/src/test/java/software/amazon/rds/common/handler/TaggingTest.java, aws-rds-cfn-common/src/test/java/software/amazon/rds/common/logging/RequestLoggerTest.java, aws-rds-cfn-test-common/pom.xml, aws-rds-customdbengineversion/pom.xml, aws-rds-dbcluster/aws-rds-dbcluster.json, aws-rds-dbcluster/pom.xml, aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/BaseHandlerStd.java, aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/Translator.java, aws-rds-dbcluster/src/test/java/software/amazon/rds/dbcluster/TranslatorTest.java, aws-rds-dbclusterendpoint/pom.xml, aws-rds-dbclusterparametergroup/pom.xml, aws-rds-dbinstance/pom.xml, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/BaseHandlerStd.java, aws-rds-dbparametergroup/pom.xml, aws-rds-dbsubnetgroup/pom.xml, aws-rds-eventsubscription/pom.xml, aws-rds-globalcluster/pom.xml, aws-rds-integration/pom.xml, aws-rds-optiongroup/pom.xml
This code change introduces support for GP3 storage type for Aurora engines. With the the storage types supported on Aurora engines, the database will now return a new StorageThroughput as a read-only parameter which will be set automatically by the backend. For more information, check the public documentation related to this feature:
https://aws.amazon.com/about-aws/whats-new/2022/11/amazon-rds-general-purpose-gp3-storage-volumes/
- Adds StorageThroughput as a read-only parameter.
- Adds and refactors unit tests for DBCluster related to StorageThroughput and Iops
- Includes missing stabilization on StorageThroughput for DBInstance resource which is already rolled-out.
- Bumps RDS SDK version to 2.24.13
By submitting this pull request, I …
=> [DBCluster] Support add support for StorageThroughput

aws-rds-integration/src/main/java/software/amazon/rds/integration/BaseHandlerStd.java, aws-rds-integration/src/main/java/software/amazon/rds/integration/CreateHandler.java, aws-rds-integration/src/main/java/software/amazon/rds/integration/DeleteHandler.java, aws-rds-integration/src/main/java/software/amazon/rds/integration/UpdateHandler.java, aws-rds-integration/src/test/java/software/amazon/rds/integration/TimeoutVerificationTest.java
Integration can take 4+ hours to create if the source database is huge. Likewise, the delete should not take more than 30 minutes, so the timeouts are being adjusted.
*Issue #, if available:* N/A
AWS::RDS::Integration can actually take 4+ hours to create/modify if the source database is huge. Likewise, the deletion should not take more than 30 minutes (as opposed to the default 90 minutes). We are adjusting the timeout values to reflect that.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice. - YES
=> [Integration] Update timeout values to work better with the service.

aws-rds-customdbengineversion/aws-rds-customdbengineversion.json, aws-rds-customdbengineversion/docs/README.md, aws-rds-customdbengineversion/pom.xml, aws-rds-customdbengineversion/resource-role.yaml, aws-rds-customdbengineversion/src/main/java/software/amazon/rds/customdbengineversion/BaseHandlerStd.java, aws-rds-customdbengineversion/src/main/java/software/amazon/rds/customdbengineversion/Translator.java, pom.xml
This code change introduces three new parameters for CustomDBEngineVersion resource.
This code change will enable customers to opt into Oracle RAC Rolling OS Patching feature and also use Custom SQLServer with Cloudformation handlers.
=> [CustomDBEngineVersion] Add support for RAC rolling OS patching

aws-rds-globalcluster/.rpdk-config, aws-rds-globalcluster/pom.xml, aws-rds-globalcluster/template.yml
Issue #, if available:
Follow up to https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-rds/pull/495, need to update JDK version to1 7 to match the commit above
Description of changes:
update jdk to jdk 17
=> [JDK] GlobalCluster Bump Java from 8 to 17

aws-rds-customdbengineversion/aws-rds-customdbengineversion.json, aws-rds-customdbengineversion/docs/README.md, aws-rds-customdbengineversion/src/main/java/software/amazon/rds/customdbengineversion/Translator.java
Previous code change introduced SourceCustomDBEngineVersionIdentifier parameter with capital `B` in DB. This change refactors the parameter casing to match the public RDS documentation with lowercase `b`.
https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_CreateCustomDBEngineVersion.html 
=> [CustomDBEngineVersion] Fix SourceCustomDbEngineVersionIdentifier casing

aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/BaseHandlerStd.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/AbstractHandlerTest.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/DeleteHandlerTest.java
This change removes OptionGroup state validation on delete DBInstance handlers logic. This will allow AWS::RDS::DBInstance resource to be deleted when an OptionGroup attached to the instance is in terminal state. This change does not impact Create or Update handlers which still fail when the member OptionGroup is in terminal state.
=> [DBInstance] Ignore OptionGroup status on Delete

aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/StorageType.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/Translator.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/TranslatorTest.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/UpdateHandlerTest.java
This request adds support for IO2 storage for DBInstance
=> [DBInstance] Add support for IO2 storage

aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/BaseHandlerStd.java
This change includes stabilization logic for DBCluster resources for `allocatedStorage` and `iops` pending modified values. Stabilization logic will wait for these values to be applied to the DBCluster before considering the resource stabilized.
=> [DBCluster] Stabilization for pending AllocatedStorage and Iops

aws-rds-dbinstance/aws-rds-dbinstance.json, aws-rds-dbinstance/docs/README.md, aws-rds-dbinstance/pom.xml, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/BaseHandlerStd.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/CallbackContext.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/CreateHandler.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/Translator.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/UpdateHandler.java
This code change adds a new parameter `AutomaticBackupReplicationKmsKeyId` to the CloudFormation DBInstance template with supporting logic to provide this parameter when enabling `AutomatedBackupsReplication`. When customers with DBInstances that have enabled `StorageEncryption` wishes to start `AutomatedBackupsReplication` in a region, they must provide a valid KMS Key in the replication region. Currently there is no way customers can provide this KMS Key via CloudFormation. 
Known limitations of the AutomatedBackupsReplication: 
- When customers have retained backups in a region they must provide the same KMS key used to encrypt those backups. 
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute …
=> [DBInstance] Support automatic replication region for encrypted storages

aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/Translator.java, aws-rds-dbcluster/src/test/java/software/amazon/rds/dbcluster/TranslatorTest.java
Include only diff of ServerlessV2ScalingConfiguration in the ModifyDBCluster that used in update handler for better consistency.
=> Only include diff of ServerlessV2ScalingConfiguration in ModifyDBCluster Call

aws-rds-cfn-common/src/main/java/software/amazon/rds/common/handler/Commons.java, aws-rds-cfn-common/src/main/java/software/amazon/rds/common/handler/TimestampContext.java, aws-rds-cfn-common/src/test/java/software/amazon/rds/common/handler/CommonsTest.java, aws-rds-customdbengineversion/src/main/java/software/amazon/rds/customdbengineversion/BaseHandlerStd.java, aws-rds-customdbengineversion/src/main/java/software/amazon/rds/customdbengineversion/CallbackContext.java, aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/BaseHandlerStd.java, aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/CallbackContext.java, aws-rds-dbclusterendpoint/src/main/java/software/amazon/rds/dbclusterendpoint/BaseHandlerStd.java, aws-rds-dbclusterendpoint/src/main/java/software/amazon/rds/dbclusterendpoint/CallbackContext.java, aws-rds-dbclusterendpoint/src/test/java/software/amazon/rds/dbclusterendpoint/CreateHandlerTest.java, aws-rds-dbclusterparametergroup/src/main/java/software/amazon/rds/dbclusterparametergroup/BaseHandlerStd.java, aws-rds-dbclusterparametergroup/src/main/java/software/amazon/rds/dbclusterparametergroup/CallbackContext.java, aws-rds-dbclusterparametergroup/src/test/java/software/amazon/rds/dbclusterparametergroup/CreateHandlerTest.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/BaseHandlerStd.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/CallbackContext.java, aws-rds-dbparametergroup/src/main/java/software/amazon/rds/dbparametergroup/BaseHandlerStd.java, aws-rds-dbparametergroup/src/main/java/software/amazon/rds/dbparametergroup/CallbackContext.java, aws-rds-dbsubnetgroup/src/main/java/software/amazon/rds/dbsubnetgroup/BaseHandlerStd.java, aws-rds-dbsubnetgroup/src/main/java/software/amazon/rds/dbsubnetgroup/CallbackContext.java, aws-rds-dbsubnetgroup/src/test/java/software/amazon/rds/dbsubnetgroup/CreateHandlerTest.java, aws-rds-eventsubscription/src/main/java/software/amazon/rds/eventsubscription/BaseHandlerStd.java, aws-rds-eventsubscription/src/main/java/software/amazon/rds/eventsubscription/CallbackContext.java, aws-rds-eventsubscription/src/test/java/software/amazon/rds/eventsubscription/CreateHandlerTest.java, aws-rds-optiongroup/src/main/java/software/amazon/rds/optiongroup/BaseHandlerStd.java, aws-rds-optiongroup/src/main/java/software/amazon/rds/optiongroup/CallbackContext.java, aws-rds-optiongroup/src/test/java/software/amazon/rds/optiongroup/CreateHandlerTest.java
_- Resource stabilization time is a time-delta that resolves the duration
  of a resource to reach a stable state after a stack creation or update._
- This was achieved by timestamping the request-start-time once and
dynamically update the request-in-progress timestamp. The delta will
be resolved every time when a stack operation is invoked.
- Added UnexpectedErrorStatus StackTrace to better identify root causes
  of such errors.
- Adapted unit tests to accept the new changes.
- Added unit test to ensure the stack trace is logged accordingly.
- Added unit test to increase test coverage.
- Testing was done in local account.
=> Adding resource stabilization time and improved UnexpectedErrorStatus

aws-rds-dbsubnetgroup/aws-rds-dbsubnetgroup.json, aws-rds-dbsubnetgroup/docs/README.md
DBSubnetGroupName validation removed to rely on RDS validation, the DBSubnetGroupName schema was also too restrictive
=> [DBSubnetGroup] Remove validation on DBSubnetGroupName

aws-rds-cfn-common/pom.xml, aws-rds-customdbengineversion/pom.xml, aws-rds-dbcluster/aws-rds-dbcluster.json, aws-rds-dbcluster/docs/README.md, aws-rds-dbcluster/pom.xml, aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/BaseHandlerStd.java, aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/Translator.java, aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/UpdateHandler.java, aws-rds-dbcluster/src/test/java/software/amazon/rds/dbcluster/UpdateHandlerTest.java, aws-rds-dbclusterendpoint/pom.xml, aws-rds-dbclusterparametergroup/pom.xml, aws-rds-dbinstance/aws-rds-dbinstance.json, aws-rds-dbinstance/docs/README.md, aws-rds-dbinstance/pom.xml, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/BaseHandlerStd.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/Translator.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/UpdateHandler.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/UpdateHandlerTest.java, aws-rds-dbparametergroup/pom.xml, aws-rds-dbsubnetgroup/pom.xml, aws-rds-eventsubscription/pom.xml, aws-rds-globalcluster/pom.xml, aws-rds-integration/pom.xml, aws-rds-optiongroup/pom.xml
This submission adds support for EngineLifecycleSupport.
DB instances and clusters can be created and restored with the EngineLifecycleSupport field via CloudFormation. All subsequent updates to this field on the resource will be blocked to prevent unintended customer resource replacement. EngineLifecycleSupport is marked as "Some Interruption" causing to preserve future compatibility for when a formal modify option is available for this field.
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/extended-support.html
=> Add EngineLifecycleSupport integration for instances and clusters 

aws-rds-eventsubscription/src/main/java/software/amazon/rds/eventsubscription/BaseHandlerStd.java
RDS EventSubscriptions recently changed the possible values of statuses on the subscription. Where if all instances in the list of sourceIds of the EventSubscription are deleted out of band, the EventSubscription goes from an active state to an all-sources-deleted state.
This change stabilizes on all-sources-deleted state.
I also discovered the following:
1. Adding valid instances to source IDs will flip an EventSubscription from `all-sources-deleted` to `active`
2. Modifying an EventSubscription's sourceType to a different sourceType will flip the EventSubscription from `all-sources-deleted` to `active`
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your …
=> fix(eventsubscription): Stabilize on all-sources-deleted status

aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/CallbackContext.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/DeleteHandler.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/AbstractHandlerTest.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/DeleteHandlerHelperTest.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/DeleteHandlerTest.java
This change fixes an issue preventing cluster instances from being deleted using Cloud Control API.
Final snapshots are not possible for read replicas and cluster instances. The issue was that the handler was determining this based on instance details provided in the request. CCAPI does not provide these details. The fix is to retrieve the instance details from RDS instead of relying on the request.
Test: unit tests and contract tests.
Issue: aws-cloudformation/cloudformation-coverage-roadmap#2013
=> fix(DBInstance): allow deleting cluster instances through CCAPI

aws-rds-cfn-common/src/main/java/software/amazon/rds/common/handler/Commons.java, aws-rds-cfn-common/src/test/java/software/amazon/rds/common/handler/CommonsTest.java, aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/CreateHandler.java, aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/UpdateHandler.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/CreateHandler.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/UpdateHandler.java
Adding Handler Action for DbInstance and DbCluster status in order to differentiate between CREATE and UPDATE resource state.
=> [Drift Detection] Adding handler action for DbInstance and DbCluster.

aws-rds-dbclusterparametergroup/src/main/java/software/amazon/rds/dbclusterparametergroup/BaseHandlerStd.java, aws-rds-dbclusterparametergroup/src/test/java/software/amazon/rds/dbclusterparametergroup/CreateHandlerTest.java
There are combinations of ParameterGroups that ModifyDBParameterGroup expected them come in the same request, as they are related and configure a particular functionality. At the same time, the ModifyDBParameterGroup API expects a maximum of 20 parameters that can be modified in a single request. (https://docs.aws.amazon.com/cli/latest/reference/rds/modify-db-parameter-group.html)
In the case that the parameters included in the CFN template exceed the request limit, we could end up in a condition in which 2 related parameters existing in the CFN template, end up in 2 different requests. We need to ensure that all related parameters are sent in the same request.
=> [DBClusterParameterGroup] Enforce that "aurora_enhanced_binlog" and "binlog_backup" get bundled in the same ModifyDBParameterGroup request

aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/Translator.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/TranslatorTest.java
This change addresses an issue causing DB instance updates to fail during rollback with an InternalFailure. The error message was "Cannot invoke 'java.lang.Integer.intValue()' because 'b' is null". The fix ensures the max() function can handle null inputs.
=> fix(DBInstance): handle cases where both previous and desired allocated storage are null

aws-rds-dbcluster/aws-rds-dbcluster.json, aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/BaseHandlerStd.java, aws-rds-dbcluster/src/test/java/software/amazon/rds/dbcluster/SchemaTest.java
Update DBCluster handler to support EnableHttpEndpoint for Aurora MySQL engine to support Data Api.
Ref: https://aws.amazon.com/about-aws/whats-new/2024/09/amazon-aurora-mysql-rds-data-api/
=> [DBCluster] Support EnableHttpEndpoint for Aurora MySQL engine to support Data Api

aws-rds-cfn-common/pom.xml, aws-rds-cfn-test-common/pom.xml, aws-rds-customdbengineversion/pom.xml, aws-rds-dbcluster/pom.xml, aws-rds-dbclusterendpoint/pom.xml, aws-rds-dbclusterparametergroup/pom.xml, aws-rds-dbinstance/pom.xml, aws-rds-dbparametergroup/pom.xml, aws-rds-dbsubnetgroup/pom.xml, aws-rds-eventsubscription/pom.xml, aws-rds-globalcluster/pom.xml, aws-rds-integration/pom.xml, aws-rds-optiongroup/pom.xml
I had a PR blocked on a coverage limit and decided the coverage report needed improving. First, all generated classes should be excluded from the report. Second, the block is applied to branch based coverage. Line based coverage shall no longer block changes. Why? A simple example: In a nested function call 'foo(bar(5))' if code is refactored to 'int x = bar(5); foo(x);' We've altered the line count and therefore the coverage ratio without any change to the code complexity or even to the AST. Branch coverage by contrast is a much closer approximation of 'has this code changed in complexity or behavior'. Thirdly, the scope of coverage is changed from PACKAGE to BUNDLE. PACKAGE makes sense for some libraries that limit interaction between package scopes. Since this repository contains …
=> Re-tuning jacoco coverage for a higher quality "you need to write more tests".

aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/Translator.java
There was a bug in autopause read handler, where when you use the SecondsUntilAutoPause property, the DBCluster resource goes drifted.
This was because the SecondsUntilAutoPause property wasn't being returned in the read handler.
=> fix(autopause) - Drift detection not including SecondsUntilAutoPause

aws-rds-dbclusterparametergroup/src/main/java/software/amazon/rds/dbclusterparametergroup/BaseHandlerStd.java, aws-rds-dbclusterparametergroup/src/main/java/software/amazon/rds/dbclusterparametergroup/CreateHandler.java, aws-rds-dbclusterparametergroup/src/main/java/software/amazon/rds/dbclusterparametergroup/ReadHandler.java, aws-rds-dbclusterparametergroup/src/main/java/software/amazon/rds/dbclusterparametergroup/UpdateHandler.java, aws-rds-dbclusterparametergroup/src/test/java/software/amazon/rds/dbclusterparametergroup/AbstractHandlerTest.java, aws-rds-dbclusterparametergroup/src/test/java/software/amazon/rds/dbclusterparametergroup/CreateHandlerTest.java, aws-rds-dbclusterparametergroup/src/test/java/software/amazon/rds/dbclusterparametergroup/UpdateHandlerTest.java
DBClusterParameterGroup was not correctly resetting parameters.
**The bug**:
Eg. Try creating a DBClusterParameterGroup with:
```
require_secure_transport: "ON"
lower_case_table_names: "1"
collation_server: "utf8_bin"
time_zone: "US/Eastern"
character_set_server: "utf8"
server_audit_events: "CONNECT,QUERY"
server_audit_logging: "1"
```
Then performing an update with:
```
lower_case_table_names: "1"
collation_server: "utf8_bin"
time_zone: "US/Eastern"
character_set_server: "utf8"
server_audit_events: "CONNECT,QUERY"
server_audit_logging: "1"
```
The parameter *require_secure_transport* does not get reset to its default value.
DBParameterGroup however, does exhibit the correct reset behaviour and resets the parameter if it is removed.
This CR ensures the …
=> CFN-564(DBClusterParameterGroup) - Fix DBClusterParameterGroup not resetting parameters

aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/ModelAdapter.java, aws-rds-dbcluster/src/test/java/software/amazon/rds/dbcluster/UpdateHandlerTest.java
Fixes an issue when null capacity is specified for Serverless V2
=> fix(DBCluster): fix NPE when null capacity specified for Serverless V2

.github/workflows/maven-verify.yml
See : https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-rds/pull/592/checks
```
Run actions/setup-python@v2.2.2
Version 3.[7](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-rds/pull/561/checks#step:4:8) was not found in the local cache
Error: Version 3.7 with arch x64 not found
The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
```
The script uses the latest version of Ubuntu and Python 3.7 is no available in this version. Hence the error. See https://github.com/actions/setup-python/issues/962#issuecomment-2414418045
This PR updates the Python to the latest version and install the relevant missing …
=> [Common] Fix the build failures caused by deprecated Python version

aws-rds-customdbengineversion/src/main/java/software/amazon/rds/customdbengineversion/BaseHandlerStd.java, aws-rds-dbclusterendpoint/src/main/java/software/amazon/rds/dbclusterendpoint/BaseHandlerStd.java, aws-rds-dbclusterparametergroup/src/main/java/software/amazon/rds/dbclusterparametergroup/BaseHandlerStd.java, aws-rds-eventsubscription/src/main/java/software/amazon/rds/eventsubscription/BaseHandlerStd.java, aws-rds-integration/src/main/java/software/amazon/rds/integration/BaseHandlerStd.java, aws-rds-optiongroup/src/main/java/software/amazon/rds/optiongroup/BaseHandlerStd.java
*Issue:*
The requestLogger in some resources is not initialized properly, resulting in a NullPointerException under certain circumstances. This causes an internal failure, preventing the customer from seeing the actual error.
This change fix the NullPointerException by making requestLogger proper initialized
=> fix: make requestLogger proper initialized

aws-rds-dbcluster/aws-rds-dbcluster.json, aws-rds-dbinstance/aws-rds-dbinstance.json
Nested properties in readOnlyProperties require their parents defined otherwise CloudFormation doesn't properly generate templates for IaC Generator: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/generate-IaC.html
=> fix(schema): Missing properties in readOnlyProperties for nested properties

aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/BaseHandlerStd.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/Translator.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/UpdateHandler.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/TranslatorTest.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/UpdateHandlerTest.java
https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/430
When an instance is autoscaled out, the template no longer matches the real instance's AllocatedStorage.
For example:
Given a template:
```
Resource:
DBInstance:
Type: AWS::RDS::DBInstance
AllocatedStorage: 100
MaxAllocatedStorage: 500
```
When the DBInstance reaches high storage utilization, it scales from AllocatedStorage 100 => AllocatedStorage 120
On template update, the ModifyDBInstance call, for ProvisionedIOPS volumes (gp3/io1/io2), will pass the template's AllocatedStorage into the ModifyDBInstance call.
This surfaces as an exception similar to:
```
Resource handler returned message: "Invalid storage size for engine name mysql and storage type gp3: …
```
=> fix(autoscale): Fix when making CFN update, an autoscaled instance should not fail the CFN deploy

aws-rds-dbinstance/aws-rds-dbinstance.json, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/BaseHandlerStd.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/DBInstancePredicates.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/Translator.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/UpdateHandler.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/util/ResourceModelHelper.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/BaseHandlerStdTest.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/DBInstancePredicatesTest.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/TranslatorTest.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/util/ResourceModelHelperTest.java
Introduce ApplyImmediately flag to allow customers to specify whether disruptive changes to the DB instance and any pending modifications are applied immediately, regardless of the PreferredMaintenanceWindow setting. If set to false, changes are applied during the next maintenance window. Until RDS applies the changes, the DB instance remains in a drift state. 
This property also determines whether the DB instance reboots when a static parameter is modified in the associated DB parameter group.
=> [DBInstance] Introduce ApplyImmediately flag to address unintended reboots and interruptions

aws-rds-cfn-common/pom.xml, aws-rds-customdbengineversion/pom.xml, aws-rds-dbcluster/pom.xml, aws-rds-dbclusterendpoint/pom.xml, aws-rds-dbclusterparametergroup/pom.xml, aws-rds-dbinstance/pom.xml, aws-rds-dbparametergroup/pom.xml, aws-rds-dbshardgroup/pom.xml, aws-rds-dbsubnetgroup/pom.xml, aws-rds-eventsubscription/pom.xml, aws-rds-globalcluster/pom.xml, aws-rds-integration/pom.xml, aws-rds-optiongroup/pom.xml
This PR cleans up the dependencies which are pulled in from the common project.
This also fixes the issue of the registered resources throwing an exception on execution of the handler:
```
Resource handler returned message: "software/amazon/awssdk/protocols/query/interceptor/QueryParametersToBodyInterceptor" (RequestToken: b9e6363a-3022-32bf-4126-bfebcc105793, HandlerErrorCode: InternalFailure)
```
This was because the `aws-cloudformation-rpdk-java-plugin` plugin was pulling in awssdk 2.19.0 dependencies: https://github.com/aws-cloudformation/cloudformation-cli-java-plugin/blob/master/pom.xml#L40
However, we are using 2.30.38.
See issue: https://github.com/aws/aws-sdk-java-v2/issues/4791
By submitting this pull request, I confirm that you can use, modify, copy, …
=> fix(dependencies): Clean up dependencies and fix outdated awssdk dependencies from aws-cloudformation-rpdk-java-plugin

.github/workflows/maven-verify.yml
[The build ](https://github.com/ccmlst/aws-cloudformation-resource-providers-rds/actions/runs/14347180118/job/40219082908) failed  due to `cloudformation-cli` generating
code with `getMaxResults()`, unsupported by Maven’s `2.1.1` plugin.
Pinning the Java plugin to `2.1.1` in the workflow ensures generated code aligns with the
runtime library, resolving the compilation error.
=> [Common] Fix CLI version mismatch

.github/workflows/maven-verify.yml, aws-rds-cfn-common/src/main/java/software/amazon/rds/common/handler/Commons.java, aws-rds-cfn-common/src/main/java/software/amazon/rds/common/util/ArnHelper.java, aws-rds-cfn-common/src/main/java/software/amazon/rds/common/validation/ValidationAccessException.java, aws-rds-cfn-common/src/main/java/software/amazon/rds/common/validation/ValidationUtils.java, aws-rds-cfn-common/src/test/java/software/amazon/rds/common/util/ArnHelperTests.java, aws-rds-dbcluster/aws-rds-dbcluster.json, aws-rds-dbcluster/resource-role.yaml, aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/BaseHandlerStd.java, aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/CallbackContext.java, aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/CreateHandler.java, aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/Translator.java, aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/util/ResourceModelHelper.java, aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/validators/ClusterScalabilityTypeValidator.java, aws-rds-dbcluster/src/test/java/software/amazon/rds/dbcluster/AbstractHandlerTest.java, aws-rds-dbcluster/src/test/java/software/amazon/rds/dbcluster/CreateHandlerTest.java, aws-rds-dbcluster/src/test/java/software/amazon/rds/dbcluster/TranslatorTest.java, aws-rds-dbcluster/src/test/java/software/amazon/rds/dbcluster/util/ResourceModelHelperTest.java, aws-rds-dbcluster/src/test/java/software/amazon/rds/dbcluster/validators/ClusterScalabilityTypeValidatorTest.java, aws-rds-dbshardgroup/src/main/java/software/amazon/rds/dbshardgroup/DeleteHandler.java
Description of changes:
Add New Parameters onto restore-db-cluster-from-snapshot And restore-db-cluster-to-point-in-time in order to support restore for Limitless Clusters.
GetClusterScalabilityTypeFromSnapshot returns default when instance snapshot is provided and when AccessException is thrown
=> [DBCluster] Support restore for Aurora Limitless Cluster

aws-rds-dbinstance/aws-rds-dbinstance.json, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/BaseHandlerStd.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/CallbackContext.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/CreateHandler.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/ReadHandler.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/Translator.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/UpdateHandler.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/util/ResourceModelHelper.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/validators/AutomaticBackupReplicationValidator.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/AbstractHandlerTest.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/CreateHandlerTest.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/ReadHandlerTest.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/UpdateHandlerTest.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/util/ResourceModelHelperTest.java
**Actions**
- Implemented new parameter AutomaticBackupReplicationRetentionPeriod. Allows setting of retention period for cross-region replicated backups and update logic changes to allow modification of replication parameters.
- Added validation for when replication parameters are specified without replication being enabled. This will now fail to prevent stack drift on update/create in these scenarios.
Ref:
[StartDBInstanceAutomatedBackupsReplication](https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_StartDBInstanceAutomatedBackupsReplication.html)
**Testing**
mvn package
=> [DBInstance] Introduce AutomaticBackupReplicationRetentionPeriod to allow setting of retention period for cross-region replicated backups

.github/workflows/maven-verify.yml, aws-rds-cfn-common/src/main/java/software/amazon/rds/common/request/ValidatedRequest.java
Description: 
Due to CLI and Maven version mismatch, we have temporarily pinned the CLI to an older version in the previous [commit](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-rds/pull/604). 
In this PR, we are : 
1. reverting the temporary fix
2. updating the validator to handle the new property MaxResult. This is to fix the compile error caused by the latest version of cloudformation-cli-java-plugin 
=> [Common] Removed the pinned cli version

aws-rds-cfn-common/src/main/java/software/amazon/rds/common/handler/Vpc.java, aws-rds-cfn-common/src/test/java/software/amazon/rds/common/handler/VpcTest.java, aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/BaseHandlerStd.java, aws-rds-dbcluster/src/test/java/software/amazon/rds/dbcluster/UpdateHandlerTest.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/UpdateHandler.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/UpdateHandlerTest.java
DBSecurity group resets to default during import
This change ensures that we never reset to default VPC when both previous and desired security group is null
=> [DBCluster][DBInstance] never reset to default VPC when both previous and desired security group is null

aws-rds-cfn-common/src/main/java/software/amazon/rds/common/error/ErrorStatus.java, aws-rds-cfn-common/src/main/java/software/amazon/rds/common/error/RetryErrorStatus.java, aws-rds-cfn-common/src/main/java/software/amazon/rds/common/handler/Commons.java, aws-rds-cfn-test-common/src/main/java/software/amazon/rds/test/common/core/AbstractTestBase.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/BaseHandlerStd.java, aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/ReadHandler.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/AbstractHandlerTest.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/CreateHandlerTest.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/DeleteHandlerTest.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/ReadHandlerTest.java, aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/UpdateHandlerTest.java
Enhanced error handling for DBInstance to return an 'In-progress' status instead of 'Fail' upon encountering throttling errors, enabling automatic retries.
=> fix (DBInstance): Handle throttling error for DBInstance resource

aws-rds-cfn-common/pom.xml, aws-rds-cfn-common/src/main/java/software/amazon/rds/common/util/WaiterHelper.java, aws-rds-dbcluster/pom.xml, aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/CallbackContext.java, aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/UpdateHandler.java, aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/util/ResourceModelHelper.java, aws-rds-dbcluster/src/test/java/software/amazon/rds/dbcluster/UpdateHandlerTest.java, aws-rds-dbshardgroup/src/main/java/software/amazon/rds/dbshardgroup/CallbackContext.java, aws-rds-dbshardgroup/src/main/java/software/amazon/rds/dbshardgroup/UpdateHandler.java
Add a delay to Aurora Serverless V2 updates, because whilst the DBCluster completes immediately, asynchronous workflows occur after the DBCluster resource is updated.
Whilst the DBCluster resource is being updated in these asynchronous workflows, resources such as DBInstances are locked out from being rebooted - but they require reboots if there are updates to DBInstances and DBParameterGroups are set to pending-reboot status.
=> fix(dbcluster) - Add delay to Aurora Serverless V2 update changes
