aws-cloudformation/aws-cloudformation-resource-providers-rds

- aws-rds-globalcluster/aws-rds-globalcluster.json
> add Engine and EngineVersion to create-only properties

- aws-rds-globalcluster/aws-rds-globalcluster.json
make resource type definition specific
> make resource type definition specific

- aws-rds-globalcluster/.rpdk-config
- aws-rds-globalcluster/pom.xml
update aws::rds sdk version to allow contract tests to pass.
> update aws::rds sdk version

- aws-rds-dbsubnetgroup/aws-rds-dbsubnetgroup.json
- aws-rds-dbsubnetgroup/inputs/inputs_1_create.json
- aws-rds-dbsubnetgroup/inputs/inputs_1_invalid.json
- aws-rds-dbsubnetgroup/inputs/inputs_1_update.json
- aws-rds-dbsubnetgroup/pom.xml
- aws-rds-dbsubnetgroup/src/main/java/software/amazon/rds/dbsubnetgroup/BaseHandlerStd.java
- aws-rds-dbsubnetgroup/src/main/java/software/amazon/rds/dbsubnetgroup/CreateHandler.java
- aws-rds-dbsubnetgroup/src/main/java/software/amazon/rds/dbsubnetgroup/DeleteHandler.java
- aws-rds-dbsubnetgroup/src/main/java/software/amazon/rds/dbsubnetgroup/ReadHandler.java
- aws-rds-dbsubnetgroup/src/main/java/software/amazon/rds/dbsubnetgroup/UpdateHandler.java
- aws-rds-dbsubnetgroup/src/test/java/software/amazon/rds/dbsubnetgroup/DeleteHandlerTest.java
- aws-rds-dbsubnetgroup/template.yml
> Changes to meet contract tests

- aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/CreateHandler.java
- aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/CreateHandlerTest.java
This commit changes CreateHandler behavior upon a cluster-member
DBInstance create. If the request requires a snapshot, it would be
rejected as the attribute is defined by the parental DBCluster object.
Links:
* https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-deletionpolicy.html
> Reject Cluster DBInstance create if snapshot is requested

- aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/DeleteHandler.java
- aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/DeleteHandlerTest.java
This commit changes AWS::RDS::DBInstance DeleteHandler behavior.
The current implementation interrupts the execution chain and returns a
resource conflict error code back. This might lead to a conflicting CFN
stack state where an out-of-bounds delete request blocks the stack
removal.
With the new behavior the handler will ignore the exception if the
instance is being deleted and go straight to the stabilization loop. In
this case it doesn't matter that an instance was modified from outside,
the handler will simply wait until the resource is gone and complete the
modification cycle.
> Ignore InvalidDBInstanceStateFault if DBInstance is being deleted

- aws-rds-cfn-common/src/main/java/software/amazon/rds/common/error/ErrorCode.java
- aws-rds-cfn-common/src/main/java/software/amazon/rds/common/handler/Commons.java
- aws-rds-dbparametergroup/src/main/java/software/amazon/rds/dbparametergroup/BaseHandlerStd.java
- aws-rds-dbparametergroup/src/main/java/software/amazon/rds/dbparametergroup/CreateHandler.java
- Adding access denied errorCode to ErrorRuleSet to handle DBParameterGroup AccessDenied .
- Handling null model parameters.
- Log handler request 
> Handle DBParameterGroup issues: Adding access denied errorCode, Null model parameters, Log request

- aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/BaseHandlerStd.java
- aws-rds-dbclusterparametergroup/src/main/java/software/amazon/rds/dbclusterparametergroup/BaseHandlerStd.java
- aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/BaseHandlerStd.java
- aws-rds-dbsubnetgroup/src/main/java/software/amazon/rds/dbsubnetgroup/BaseHandlerStd.java
- aws-rds-eventsubscription/src/main/java/software/amazon/rds/eventsubscription/BaseHandlerStd.java
- aws-rds-optiongroup/src/main/java/software/amazon/rds/optiongroup/BaseHandlerStd.java
logging handler request in DBInstance, DBCluster, DBClusterParameterGroup, EventSubscription, and DBSubnetGroup
> Logging handler request

- aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/BaseHandlerStd.java
- aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/CreateHandler.java
- aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/Translator.java
- aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/UpdateHandler.java
Introducing access denied soft-fail while adding/updating tags for DBCluster
> [DBCluster]Add soft failing for DBCluster

- aws-rds-dbclusterparametergroup/src/main/java/software/amazon/rds/dbclusterparametergroup/BaseHandlerStd.java
- Log handler request and handler response
- Use logging proxy to log all DBClusterParameterGroup interactions with RDS client. 
> [DBClusterParameterGroup]Use logging proxy in DBClusterParameterGroup

- aws-rds-cfn-common/src/main/java/software/amazon/rds/common/handler/Tagging.java
- aws-rds-dbparametergroup/src/main/java/software/amazon/rds/dbparametergroup/BaseHandlerStd.java
Use tagging `bestEffort` method while handling tags operations exceptions. 
> [DBParameterGroup]Use common BestEffort method while handling Tags Exception

- aws-rds-dbcluster/aws-rds-dbcluster.json
Accept aurora-postgresql engine in schema
> [DBCluster] Accept aurora-postgresql engine in schema

- aws-rds-dbsubnetgroup/aws-rds-dbsubnetgroup.json
> [DBSubnetGroup] Fix DBSubnetGroupName Pattern

- aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/DeleteHandler.java
- aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/DeleteHandlerTest.java
This commit updates DBInstance.deleteHandler behavior. RDS API rejects a delete request with a final snapshot identifier if an instance is either a read replica or a member of a db cluster. This commit explicitly disables a final snapshot identifier compute if one of the aforementioned conditions is met.
> [DBInstance] Disable final snapshot for replicas and cluster instances

- aws-rds-dbparametergroup/aws-rds-dbparametergroup.json
- aws-rds-dbparametergroup/docs/README.md
`Description` and `Family` parameters are immutable and need replacement upon change. 
> [DBParameterGroup]Add Description and Family to createOnlyProperties

- aws-rds-dbclusterparametergroup/src/main/java/software/amazon/rds/dbclusterparametergroup/BaseHandlerStd.java
- aws-rds-dbparametergroup/src/main/java/software/amazon/rds/dbparametergroup/BaseHandlerStd.java
Adding null safety check to invalid parameters condition against newParameterValue. 
> [DBParameterGroup][DBClusterParameterGroup]Add Null Check to Invald Parameter Condition

- aws-rds-dbparametergroup/src/main/java/software/amazon/rds/dbparametergroup/BaseHandlerStd.java
Guard Against Null Context in `handleRequest` in BashHandler.
> [DBParameterGroup] Guard Against Null Context in `handleRequest`

- aws-rds-eventsubscription/src/main/java/software/amazon/rds/eventsubscription/BaseHandlerStd.java
Add SnsTopicArnNotFoundException to Default Error Rule Set.
> [EventSubscription] Add SnsTopicArnNotFoundException to Default Error Rule Set

- aws-rds-dbclusterparametergroup/src/main/java/software/amazon/rds/dbclusterparametergroup/CreateHandler.java
- aws-rds-dbclusterparametergroup/src/test/java/software/amazon/rds/dbclusterparametergroup/CreateHandlerTest.java
When customer specify stack IAM role with tag conditions. Create call will fail with `AccessDenied` exception because it contains only system tags and apply other tags by `AddTagsToResource`.
I.e: Customer created this stack with stack level tag `foo -> bar`
```
AWSTemplateFormatVersion: 2010-09-09
Description: RDS DBClusterParameterGroup Example Stack
Resources:
RDSDBClusterParameterGroup:
Type: AWS::RDS::DBClusterParameterGroup
DeletionPolicy: Delete
Properties:
Parameters:
character_set_database: utf32
Family: aurora5.6
Description: "Any Description"
```
And assigned IAM Role to execute this stack
```
{
"Version": "2012-10-17",
"Statement": [
{
"Sid": "VisualEditor0",
"Effect": "Allow",
"Action": "rds:*",
"Resource": "*",
"Condition": {
"StringEquals": { …
```
> [DBClusterParameterGroup] Handle Create Call while Stack Having IAM Role with Tag Condition

- aws-rds-dbparametergroup/src/main/java/software/amazon/rds/dbparametergroup/CreateHandler.java
- aws-rds-dbparametergroup/src/test/java/software/amazon/rds/dbparametergroup/CreateHandlerTest.java
When customer specify stack IAM role with tag conditions. Create call will fail with `AccessDenied` exception because it contains only system tags and apply other tags by `AddTagsToResource`.
I.e: Customer created this stack with stack level tag `foo -> bar`
```
AWSTemplateFormatVersion: 2010-09-09
Description: RDS DBParameterGroup Example Stack
Resources:
RDSDBParameterGroup:
Type: AWS::RDS::DBParameterGroup
DeletionPolicy: Delete
Properties:
Parameters:
character_set_database: utf32
Family: mysql.6
Description: "Any Description"
```
And assigned IAM Role to execute this stack
```
{
"Version": "2012-10-17",
"Statement": [
{
"Sid": "VisualEditor0",
"Effect": "Allow",
"Action": "rds:*",
"Resource": "*",
"Condition": {
"StringEquals": {
"rds:req-tag/foo": "bar"
}
} …
```
> [DBParameterGroup] Handle create call while stack having IAM role with specific tag condition

- aws-rds-dbsubnetgroup/src/main/java/software/amazon/rds/dbsubnetgroup/CreateHandler.java
Adding system tags to all tags set.
> [DBSubnetGroup] Adding System Tags To All Tags

- aws-rds-eventsubscription/docs/README.md
> [EventSubscription] Update READ.me file

- aws-rds-dbclusterparametergroup/src/main/java/software/amazon/rds/dbclusterparametergroup/BaseHandlerStd.java
- aws-rds-dbclusterparametergroup/src/main/java/software/amazon/rds/dbclusterparametergroup/Translator.java
- aws-rds-dbclusterparametergroup/src/test/java/software/amazon/rds/dbclusterparametergroup/CreateHandlerTest.java
This is a port of changes in #231 for DBClusterParameterGroup. 
> [DBClusterParameterGroup] Fix stackoverflow related to request logging

- aws-rds-optiongroup/inputs/inputs_1_create.json
- aws-rds-optiongroup/inputs/inputs_1_invalid.json
- aws-rds-optiongroup/inputs/inputs_1_update.json
> [OptionGroup] Fixed inputs

- aws-rds-cfn-common/pom.xml
- aws-rds-dbcluster/pom.xml
- aws-rds-dbclusterendpoint/pom.xml
- aws-rds-dbclusterparametergroup/pom.xml
- aws-rds-dbinstance/pom.xml
- aws-rds-dbparametergroup/pom.xml
- aws-rds-dbsubnetgroup/pom.xml
- aws-rds-eventsubscription/pom.xml
- aws-rds-globalcluster/pom.xml
- aws-rds-optiongroup/pom.xml
This PR bumps SDK version to the latest one
> [Common] Bump SDK version to the latest one

- aws-rds-cfn-test-common/src/main/java/software/amazon/rds/test/common/verification/AccessPermissionVerificationMode.java
This PR implements description method in AccessPermissionVerificationMode
> [Common] Add implementation for description method

- aws-rds-dbinstance/aws-rds-dbinstance.json
- aws-rds-dbinstance/docs/README.md
- aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/Translator.java
- aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/ListHandlerTest.java
This PR introduces support for the parameter ReplicaMode
> [DBInstance] Added support for ReplicaMode

- aws-rds-dbinstance/aws-rds-dbinstance.json
The Monitoring Interval is always mutable. This PR addresses this oversight.
> [DBInstance] Fix Immutability for Monitoring Interval

- aws-rds-dbinstance/aws-rds-dbinstance.json
- aws-rds-dbinstance/docs/README.md
Fix typo in StorageThroughput attribute name
> [DBInstance] Fix typo in StorageThroughput attribute

- aws-rds-customdbengineversion/pom.xml
This resolves #352 by removing extraneous dependency on log4j altogether.
> [CEV] Remove log4j dependency

- aws-rds-dbinstance/aws-rds-dbinstance.json
Lowercase transform SourceDBInstanceAutomatedBackupsArn
> [DBInstance] Lowercase transform SourceDBInstanceAutomatedBackupsArn

- aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/BaseHandlerStd.java
- aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/CreateHandler.java
- aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/Translator.java
- aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/util/ResourceModelHelper.java
- aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/CreateHandlerTest.java
- aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/TranslatorTest.java
- aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/util/ResourceModelHelperTest.java
This PR fixes an issue introduced in #384 with regards to SQL Server instances which not yet support the parameter.
> [DBInstance] Use modify call to set storage size for SQLServer

- aws-rds-dbparametergroup/src/main/java/software/amazon/rds/dbparametergroup/BaseHandlerStd.java
This commit limits the parameter name filter size to 100 elements per request. RDS API would reject a request containing more than 100 parameter names in the filter. The commit removes the recursive progressChain tailing and uses a simplistic sequential current parameter accumulator buildup.
This commit is a follow-up on https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-rds/pull/392.
> [DBParameterGroup] Limit max parameter name filter size to 100

- aws-rds-cfn-test-common/src/main/java/software/amazon/rds/test/common/schema/ResourceDriftTestHelper.java
This commit is a minor cleanup in
ResourceDriftDetector.assertResourceNotDrifted that is aiming to optimize recursive allocations.
> [Test-Common] Cleanup ResourceDriftDetector

- aws-rds-cfn-common/src/main/java/software/amazon/rds/common/handler/Events.java
- aws-rds-cfn-common/src/test/java/software/amazon/rds/common/handler/EventsTest.java
This commit alters the range of the RDS event categories that are being fetched upon a create/update operation. In particular, it adds an extra category called `maintenance`. The exact event category choice is API-specific and could differ between RDS resources.
> [Common] Fetch events of types notification and maintenance

- aws-rds-cfn-test-common/src/main/java/software/amazon/rds/test/common/core/ServiceProvider.java
- aws-rds-customdbengineversion/aws-rds-customdbengineversion.json
- aws-rds-customdbengineversion/docs/README.md
- aws-rds-customdbengineversion/docs/tag.md
- aws-rds-customdbengineversion/resource-role.yaml
- aws-rds-customdbengineversion/src/main/java/software/amazon/rds/customdbengineversion/BaseHandlerStd.java
- aws-rds-customdbengineversion/src/test/java/software/amazon/rds/customdbengineversion/CreateHandlerTest.java
This PR adds 
- needed permission for create CustomDBEngineVersion.
Documentation: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/custom-setup-orcl.html#custom-setup-orcl.iam-user
- Ensure CEVArn is filled in tagging step.
> [CustomDBEngineVersion] Add needed permission

- aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/CreateHandler.java
- aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/CreateHandlerTest.java
This commit fixes a faulty behavior on a corner case when an instance is being restored from a snapshot and its engine is not explicitly set but MultiAZ is set to false. The current implementation instructs the handler to fetch the snapshot only if MultiAZ is unset. The engine data is used later on to detect the required storage type modifications.
> [DBInstance] Handle a restore from snapshot when MultiAZ=false

- aws-rds-optiongroup/src/main/java/software/amazon/rds/optiongroup/BaseHandlerStd.java
- aws-rds-optiongroup/src/main/java/software/amazon/rds/optiongroup/ClientBuilder.java
- aws-rds-optiongroup/src/main/java/software/amazon/rds/optiongroup/CreateHandler.java
- aws-rds-optiongroup/src/main/java/software/amazon/rds/optiongroup/Translator.java
- aws-rds-optiongroup/src/main/java/software/amazon/rds/optiongroup/UpdateHandler.java
Fix static code analysis rules regarding import order, overloaded methods and constant variable naming conventions.
> [OptionGroup] Fix checkstyle violations

- aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/Translator.java
- aws-rds-dbcluster/src/test/java/software/amazon/rds/dbcluster/AbstractHandlerTest.java
- aws-rds-dbcluster/src/test/java/software/amazon/rds/dbcluster/CreateHandlerTest.java
- aws-rds-dbcluster/src/test/java/software/amazon/rds/dbcluster/TranslatorTest.java
This change handles RestoreType parameter in RestoreDbClusterToPointInTimeRequest. 
*Testing:*
Tests were added to cover the request looking for explicit parameters. Manual tests were also conducted by registering a private handler to the resource and observing the request parameters submitted in the request.
> Restore type

- aws-rds-dbsubnetgroup/aws-rds-dbsubnetgroup.json
This PR moves permissions from read handler to create handler, as intended
> [DBSubnetGroup] Move required permissions to correct handler

- aws-rds-dbclusterparametergroup/aws-rds-dbclusterparametergroup.json
- aws-rds-dbparametergroup/aws-rds-dbparametergroup.json
- aws-rds-eventsubscription/aws-rds-eventsubscription.json
- aws-rds-optiongroup/aws-rds-optiongroup.json
This PR duplicates logic from #462 to other resources that were missing such permissions.
> [DBEventSubscription][OptionGroup][DBParameterGroup][DBClusterParameterGroup] explicitly add add/remove tags permissions

- aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/Translator.java
- aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/TranslatorTest.java
Fix incorrect Update Handler code for DedicatedLogVolumeSplit
> [DBInstance] Fix Update handing of DedicatedLogVolumeSplit

- aws-rds-globalcluster/.rpdk-config
- aws-rds-globalcluster/template.yml
[GlobalCluster] upgrade Java runtime version from Java 8 to Java 11
> update globalCluster lambda runtime version

- aws-rds-integration/aws-rds-integration.json
The new description is document writer approved.
*Issue #, if available:* N/A
*Description of changes:* The previous description was not correct.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice. - I AGREE
> Update the resource decription for AWS::RDS::Integration

- .gitignore
- README.md
- aws-rds-cfn-common/pom.xml
- aws-rds-customdbengineversion/docs/README.md
- aws-rds-customdbengineversion/pom.xml
- aws-rds-dbcluster/docs/README.md
- aws-rds-dbcluster/pom.xml
- aws-rds-dbclusterendpoint/pom.xml
- aws-rds-dbclusterparametergroup/pom.xml
- aws-rds-dbinstance/pom.xml
- aws-rds-dbparametergroup/pom.xml
- aws-rds-dbsubnetgroup/pom.xml
- aws-rds-eventsubscription/pom.xml
- aws-rds-globalcluster/pom.xml
- aws-rds-integration/aws-rds-integration.json
- aws-rds-integration/docs/README.md
- aws-rds-integration/pom.xml
- aws-rds-integration/resource-role.yaml
- aws-rds-integration/src/main/java/software/amazon/rds/integration/BaseHandlerStd.java
- aws-rds-integration/src/main/java/software/amazon/rds/integration/CreateHandler.java
- aws-rds-integration/src/main/java/software/amazon/rds/integration/DeleteHandler.java
- aws-rds-integration/src/main/java/software/amazon/rds/integration/Translator.java
- aws-rds-integration/src/main/java/software/amazon/rds/integration/UpdateHandler.java
- aws-rds-integration/src/test/java/software/amazon/rds/integration/AbstractHandlerTest.java
- aws-rds-integration/src/test/java/software/amazon/rds/integration/CreateHandlerTest.java
- aws-rds-integration/src/test/java/software/amazon/rds/integration/TranslatorTest.java
- aws-rds-integration/src/test/java/software/amazon/rds/integration/UpdateHandlerTest.java
- aws-rds-optiongroup/pom.xml
This commit adds support for new attributes DataFilter and Description. The resource can now also modify IntegrationName. The SDK version is updated to get access to the new fields.
*Issue #, if available:* #518
[Integration] Add support for Table-Level filtering
This commit adds support for new attributes DataFilter and Description.
The resource can now also modify IntegrationName.
Co-authored-by: Justin Chen <jutchen@amazon.com>
YES
Please note the content of the PR was already reviewed internally by @dbbh and @moataz-mhmd.
> [Integration] Add support for Table-Level filtering

- aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/Translator.java
Includes the PI KMSKeyId in the model when changing PI retention period
> [DBInstance] Set KMSKeyId when adjusting PI retention period.

- aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/BaseHandlerStd.java
- aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/CreateHandler.java
- aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/DBInstancePredicates.java
- aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/DeleteHandler.java
- aws-rds-dbinstance/src/main/java/software/amazon/rds/dbinstance/UpdateHandler.java
- aws-rds-dbinstance/src/test/java/software/amazon/rds/dbinstance/BaseHandlerStdTest.java
*Issue:* CFN-27
*Description of changes:* Breaking down a high churn PR, for discussion see
https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-rds/pull/574
> [Refactoring] Decomposing DBInstance BaseHandlerStd in advance of expanding the DBInstance type.

- aws-rds-dbshardgroup/aws-rds-dbshardgroup.json
- aws-rds-dbshardgroup/src/main/java/software/amazon/rds/dbshardgroup/CreateHandler.java
- aws-rds-dbshardgroup/src/main/java/software/amazon/rds/dbshardgroup/Translator.java
- aws-rds-dbshardgroup/src/test/java/software/amazon/rds/dbshardgroup/CreateHandlerTest.java
[DBShardGroup] Introduce tag-on-create behavior
> [DBShardGroup] Introduce tag-on-create behavior
